### ISSUE TITLE
Add download artifacts indexer for new releases

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#10]
As we'll probably want to be self-hosting out of S3 anyways (instead of osf.io), add an indexer staep somewhere where to make the directories navigable with S3/CF hosting.

**Comment by cmungall** [comment]
The index will make it easier for curators and GAF providers to find reports for their GAF

**Comment by kltm** [comment]
Actually, now that I've added some metainfo to the s3 objects, I may actually be able to do the remote indexer more sensibly, which would solve some problems with current indexing and pushing schemes, as well as proposed historical ones.
The same script would have a "capper" mode, a fully "recursive mode", and an option to point one parent above the current root (for use with the "capper").

**Comment by kltm** [comment]
Good PR from @dougli1sqrd . Will check against experimental.

**Comment by kltm** [comment]
Needs testing on `release` and `snapshot`.

**Comment by kltm** [comment]
Okay, this seems to be working pretty good now.
