### ISSUE TITLE
Ontology snapshots are not updating/being deployed

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/pipeline#105]
purl.obolibrary.org/obo/go/snapshot/go-basic.obo
Most recent is 6/28
No updates are getting in (including a fix removing a spurious tab in the comments that is breaking loading this file at MGI).

**Comment by hdrabkin** [comment]
Follow up
The current editor's obo file has my fix. No Tab in comment for GO:0042626
It IS in the go-basic.obo taken from above purl.

**Comment by kltm** [comment]
For now, I'm guessing that it's a combination of lagginess, the snapshot failing recently, and geneontology/pipeline#90 . That said, until we have #90 squared away, it's a little hard to debug. I'm going to let snapshot run as normal and check again to see if it clears.

**Comment by hdrabkin** [comment]
Right; 
I got a qc failure report this morning for the attempted load of July 4, 2019 at 9:44 PM. Same issue (aberrant tab, date stamp still 6/28). So nothing has changed yet. Will keep you appraised.

**Comment by kltm** [comment]
That would be expected--the `snapshot` build failed again yesterday. It does seem to be running better today:
https://build.geneontology.org/job/geneontology/job/pipeline/job/snapshot/

**Comment by hdrabkin** [comment]
As of yesterday, the snapshots are updating properly and for two days in a row, I do not get "GO Load Failed" Qc emails. 
I will close this now.

**Comment by kltm** [comment]
`snapshot` status can always be seen here: https://build.geneontology.org/job/geneontology/job/pipeline/job/snapshot/
Given `snapshot` failure frequencies, it only send email to developers right now.
That said, the "real" issue--the ontology dates being off--is still underway.
