### ISSUE TITLE
Add Apache Jena (riot command)

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#11]
For the users.yaml and groups.yaml to be properly consumed, we'll need the `riot` command in apache jena added to the machines or the used software stack.

**Comment by kltm** [comment]
See https://github.com/geneontology/go-site/pull/488 with @balhoff

**Comment by cmungall** [comment]
can we use robot instead, less direct dependencies

**Comment by balhoff** [comment]
I’ll give it a try.

**Comment by balhoff** [comment]
No longer needed; changed to use ROBOT in https://github.com/geneontology/go-site/pull/493.
