### ISSUE TITLE
1/5th of our bioentities are of type gene_products

### ISSUE THREAD

**Issue by lpalbou** [geneontology/pipeline#112]
Looking at the [stats](https://geneontology.s3.amazonaws.com/go-stats.json):

<img width="354" alt="Screen Shot 2019-07-17 at 3 17 40 PM" src="https://user-images.githubusercontent.com/24249870/61415615-06955c00-a8a6-11e9-8f1c-a2e04302760e.png">

About 1/5th of our bioentities are described as generic gene_products without detailing if they are proteins, genes or rna. We discussed this with @thomaspd and it seems it concerns mostly [AspGD and CGD bioentities](http://golr-aux.geneontology.io/solr/select?fq=document_category:"annotation"&fq=type:gene_product&q=*:*&wt=json&rows=0&facet=true&facet.field=assigned_by&facet.limit=10000&facet.mincount=1) but also TAIR, FlyBase and GO_Central to a lesser extent:

<img width="191" alt="Screen Shot 2019-07-17 at 3 23 43 PM" src="https://user-images.githubusercontent.com/24249870/61415880-de5a2d00-a8a6-11e9-86f0-cf118ee56a3b.png">

**Comment by kltm** [comment]
@lpalbou What is the proposed action or question here?

**Comment by thomaspd** [comment]
I think we should discuss with these annotation groups to encourage them to either label them all as   type "gene", or be more precise about the type of product ("protein" or "RNA") like the other groups.

**Comment by pgaudet** [comment]
I don' like 'gene' because I think we do want to make the distinction between a gene and a gene product, for example when we annotate targets of transcription factors. 

However it should be doable for the different groups to provide more precise information - 
@tberardini @marekskrzypek @hatrill : would it be possible for you to change ? 

I am curious to know what the GOC annotations to gene_product are. Are we using the same type provided by the original database ? 

Thanks, 
Pascale

**Comment by marekskrzypek** [comment]
I suppose it should be possible, once a decision is reached.

**Comment by pgaudet** [comment]
@marekskrzypek Are you annotating proteins ? If that's the case, it's be great if you could make the switch to the more precise term in your GAF. 

Pascale

**Comment by tberardini** [comment]
We use 'gene_product' for cases where we are annotating genetic loci (uncloned genes). They are most likely protein coding genes but we don't know that for sure and therefore want to hedge our bets and annotate to 'gene_product' instead.

**Comment by pgaudet** [comment]
This is not a pipeline issue. I moved the comments here: 

https://github.com/geneontology/go-site/issues/204
