### ISSUE TITLE
Make a Docker base for basic functionalities (change python versioning over to using an appropriate Docker images)

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#115]
We want to make sure that any even slightly specialized computing done in the pipeline is done within the context of a standard base docker image, rather than creating an ever more complicated base system environment.

These images should be based on a TBD environment, likely Ubuntu Minimal.

Specifically, currently, we're adding an extra-operations python 3.6 package to ensure that we're not blocking work while we wait for a more permanent docker solution (i.e. https://github.com/geneontology/pipeline/pull/114 should be reverted).

Tagging @dougli1sqrd

**Comment by dougli1sqrd** [comment]
This https://github.com/geneontology/operations/pull/38 is an initial dev-base docker image that we can use in the go-site pipeline Makefile megastep. 

This https://github.com/geneontology/pipeline/pull/119 is a PR for what the dockerized megastep should look like once we are ready. It utilizes the image made in the above PR.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/operations/pull/38#issuecomment-535268807

**Comment by kltm** [comment]
E.g. geneontology/dev-base:eb2f253bb0ff780e1b623adde6d5537c55c31224_2019-08-13T163314
