### ISSUE TITLE
Add gaferencer for all targets to the pipeline

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#116]
Add gaferencer for all targets to the pipeline.

@dougli1sqrd Let's use this as the center for the gaferencer work.

**Comment by dougli1sqrd** [comment]
This https://github.com/geneontology/go-site/pull/1147 will bring us into the taxon check world and using gaferencer in the megamake. 

This ticket is a dependency though: https://github.com/geneontology/pipeline/issues/115

**Comment by dougli1sqrd** [comment]
Gaferencer now running in the wild on all sources.
