### ISSUE TITLE
Some ontology files have incorrect date

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#123]
Looking at the current contents of http://skyhook.berkeleybop.org/release/ontology/ for the current `release` attempt, it appears that the date is not getting locked in as expected from the fix being rolled out in #95 . For example, the 2019-09-01 release attempt:

 http://skyhook.berkeleybop.org/release/ontology/go-basic.obo

has `data-version: releases/2019-08-31`.
This error seems to be true for most of products: go.obo, go.owl, go-base.owl.

Approaches might be to make sure that the pipeline is actually using the fix from #95 (or is it being held back for some reason?), that the fix is effective, then check for new problems.

Reported by @pgaudet 
Tagging @balhoff 

Possibly relates to #95 ?

**Comment by kltm** [comment]
Note that this error is not necessarily blocking the release, but may require a mapping to be added by @balhoff as we did before.

**Comment by kltm** [comment]
@pgaudet I'm assuming that we want to fix this sooner rather than later. I've added to the project.

**Comment by pgaudet** [comment]
Yes, I think this is important, since we use the dates to track release versions. Dates not matching are confusing to users.

**Comment by kltm** [comment]
@balhoff @dougli1sqrd I'd note that looking at the logs in the ontology build:
```
12:03:58  2019-09-06 19:03:58,387 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=SubClassOf(<http://purl.obolibrary.org/obo/WBbt_0005404> owl:Thing), referencedObject=<http://purl.obolibrary.org/obo/WBbt_0005404>, category=DEPRECATED]
```
The first number is what Jenkins knows, the second what the robot image is reporting.
That would seem to indicate that either the fix did not take or was not applied.

**Comment by kltm** [comment]
@balhoff @dougli1sqrd I was wondering if you had any thoughts on this one. It may be that just supplying the date is insufficient if the image "wall clock" is off enough and in the wrong timezone.

**Comment by dougli1sqrd** [comment]
I'll look into this later on today.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/pipeline/pull/125 is my suggestion.

**Comment by kltm** [comment]
Fix now in `master`; let's check results tomorrow afternoon.

**Comment by kltm** [comment]
Okay, we (likely @kltm ) seem to have reverted it out of `master` at some point.
Re-adding manually.

**Comment by kltm** [comment]
I think we're likely done here? We can reopen if not.
