### ISSUE TITLE
Dockerize pipeline Mega-step (GAF, etc.) to support ontobio and python versions

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#133]
Adding just the changes that will get the dockerization to work in go-site Makefile
See branch `the_great_merging_branch`
https://github.com/geneontology/go-site/tree/the_great_merging_branch
See https://github.com/geneontology/pipeline/pull/132

**Comment by kltm** [comment]
Took PR.

**Comment by dougli1sqrd** [comment]
@kltm since snapshot is running this, I think we can call this closed?
