### ISSUE TITLE
snapshot gaf for MGI has blank lines between header and data 

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/pipeline#142]
http://snapshot.geneontology.org/annotations/mgi.gaf.gz
 The are about 24 blank lines right after the header records and then there’s 4 more starting at around line 355249. We use this gaf to get our PAINT annotations; lines have to be manually removed for scripts to pull them out not to bomb.

Harold

**Comment by kltm** [comment]
@hdrabkin Yeah, that is super not good.

@dougli1sqrd Can you take a look at this? As well, it might be good to see is blanks are part of the spec and if we can parse this file ourselves--that might be a cheap crosscheck to add.

**Comment by kltm** [comment]
@hdrabkin There should be a fix that should be exposed in the data sometime tomorrow night.
Apologies for the trouble with that.

**Comment by dougli1sqrd** [comment]
@hdrabkin Checking snapshot it looks like it's fixed?

**Comment by hdrabkin** [comment]
I have had no contacts from our SEs about load failures and in fact looking at the file now, the extra lines are gone. So I guess this can be closed. Thanks
