### ISSUE TITLE
Sanity check failure due to upstream downloader problem

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/pipeline#147]
Over the last weekend (Nov 24) we had a pipeline failure during the Sanity Check. 

The Sanity Check found a xenbase.gpi file as a source, but no corresponding outputs, and failed the pipeline. 

This is similar to an issue we have had before where the downloader was set too aggressive and downloaded upstream sources when it should not have, confusing the sanity check. In this case, we have a Makefile target for upstream sources, so that when gaferencer is run in local modes of the pipeline (not on Jenkins) sources will still be downloaded. In the Jenkins mode though, sources are downloaded in a separate step beforehand, and then placed where make will expect them. The  makefile target to download the sources is still run, but it's set to skip the download for any existing sources it finds.

However, since xenbase only has a gpi file, and the Makefile download target is set to download gpi as well, xenbase became a source for the sanity checker to look at. 

The solution here is simple, and is to just remove the option `--gpi` which will stop the downloader from downloading missing gpis. We do not need this anyway as we build the GPIs ourselves in the course of the pipeline run currently.

A fix for this went in Sunday.

**Comment by kltm** [comment]
https://github.com/geneontology/go-site/commit/4747cd416a6734db42f74d695dba68b040a944e1

**Comment by dougli1sqrd** [comment]
We passed the sanity check, so I will close the ticket.
