### ISSUE TITLE
Release QC Automatization - step 1

### ISSUE THREAD

**Issue by pgaudet** [geneontology/pipeline#164]
Hello, 

As a first step to automatizing the check that I do for the releases, it would be nice that for each snapshot, any change of more than 5% of any line in the go-annotation-changes.json file would send an email to 'go-quality@mailman.stanford.edu' with the list of the problematic lines and the json hierarchy - for example
detailed changes > annotations > by_taxon >  NCBITaxon:10116\|Rattus norvegicus | "-53015 / 454029 (-11.68%) "

This way I can start troubleshooting the problem as it happens, and not at the release step. 

Thanks, Pascale

@lpalbou @kltm

**Comment by kltm** [comment]
Likely a dupe of
https://github.com/geneontology/go-site/issues/1062

**Comment by pgaudet** [comment]
OK - I added to the ticket that we need this check on snapshop.
