### ISSUE TITLE
noctua-models synchonization failed

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/pipeline#171]
Asking for Li
A model made in Noctua and marked production on 3/24/20 is not showing up in the snapshote gpad file (http://snapshot.geneontology.org/products/annotations/noctua_mgi.gpad.gz)
Header says it's 3-30-20.
Is there a problem? gomodel:5e72450500000653
Thanks

**Comment by kltm** [comment]
Yes, thank you--there was a problem. The github push step got hung up for some reason on credentials. I've manually pushed and am looking into it.

**Comment by kltm** [comment]
I'm unsure what happened there. We'll try and keep an eye on it.
