### ISSUE TITLE
Test upcoming PANTHER 15.0 release

### ISSUE THREAD

**Issue by dustine32** [geneontology/pipeline#177]
Test run to check for any problems with new data. This new pipeline branch will point to PANTHER 15.0 `tree_files.tar.gz` and `names.tab` along with IBA GAFs generated from these trees. IBA file URLs are in https://github.com/geneontology/go-site/commit/8dbe4137d8e3d58e10a3676bfec7bea96b41197e branch `dustine32-issue-1488`. Ticket in `go-site` is https://github.com/geneontology/go-site/issues/1488.

**Comment by kltm** [comment]
@dustine32 You good here now, right?

**Comment by kltm** [comment]
Make the PR against `master` and then feel free to close.

**Comment by dustine32** [comment]
@kltm Yep, thanks! PR is https://github.com/geneontology/pipeline/pull/179.
