### ISSUE TITLE
Handle "Method code too large" error - look at offloading code outside pipeline block

### ISSUE THREAD

**Issue by dustine32** [geneontology/pipeline#183]
[This version](https://github.com/geneontology/pipeline/blob/cdf873cbb6ca003ba389fe6ed53416f13cfbf191/Jenkinsfile) (and a few others) of `Jenkinsfile` causes the Jenkins pipeline to immediately [throw a "Method code too large" error](https://build.geneontology.org/job/geneontology/job/pipeline/job/master/547/console):

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during class generation: Method code too large!

java.lang.RuntimeException: Method code too large!
   ...
```

According to this [article](https://support.cloudbees.com/hc/en-us/articles/360039361371-Method-Code-Too-Large-Error) it's literally due to the `Jenkinsfile`'s `pipeline{}` block containing too much code. Suggested solutions are to move some of the code to external scripts or groovy methods outside the `pipeline{}` block.

I'll branch off of the above `Jenkinsfile` commit https://github.com/geneontology/pipeline/commit/cdf873cbb6ca003ba389fe6ed53416f13cfbf191 to experiment with the groovy syntax route.

**Comment by lpalbou** [comment]
There are a number of things that could be grouped into a single script each time (eg creating directories; downloading x files). I am unsure also why we manually reference each GAF on release/snapshot but probably to kind of use the same script for master where you want to manually set the species.. Making it hardcoded could however produce errors too.

**Comment by kltm** [comment]
Yes, that is definitely one of the approaches that will be explored (and was used to get the taxon constraints out the door, folding things into a Makefile). It's nice to have things on the surface for debugging, but we'll start folding things away if we have to. Initially, we tried adjusting the JVM; currently, @dustine32 was going to explore a small juggle in the code layout to bypass the issue.

**Comment by dustine32** [comment]
I'll break down my testing by commit:
1. https://github.com/geneontology/pipeline/commit/cdf873cbb6ca003ba389fe6ed53416f13cfbf191 - Initial testing state.
[Result](https://build.geneontology.org/job/geneontology/job/pipeline/job/issue-183-code-too-large/2/console): This reproduces the "Code too large" error on Jenkins.
2. https://github.com/geneontology/pipeline/commit/b22cc2042882cb18917cee547a2dcc07d1650c72 - Test that commenting out of code lines in `pipeline` block will resolve the error in Jenkins.
[Result](https://build.geneontology.org/job/geneontology/job/pipeline/job/issue-183-code-too-large/3/execution/node/22/log/): pipeline fails right away but with message `Only master can touch that target` because this test branch is pointing to `TARGET_BUCKET` `go-data-product-experimental`. This immediate bail out is OK and actually really convenient for testing.
3. https://github.com/geneontology/pipeline/commit/a65d9ebb8cdb48558687b5dd0037b9d60f044696 - Add 11 dummy `echo` command lines inside the `pipeline` block to trigger "Code too large" error again.
[Result](https://build.geneontology.org/job/geneontology/job/pipeline/job/issue-183-code-too-large/4/console): The "Code too large" error is back. Hooray.
4. https://github.com/geneontology/pipeline/commit/78c548b4d7ea364711bf8e53c6aa116ec9f65553 - Move `echo` cmd lines outside `pipeline` block to new method `callThoseEchos()` and call new method from same location (mega-step) in `pipeline` block.
[Result](https://build.geneontology.org/job/geneontology/job/pipeline/job/issue-183-code-too-large/5/execution/node/22/log/): "Code too large" error does not occur. We make it past that to the now familiar `Only master can touch that target` error.
5. https://github.com/geneontology/pipeline/commit/d244ad4feb37cfcf5e7e2ae6d6bf87f3f95c190b - Actually run new method by placing before the `Only master can touch that target` check.
[Result](https://build.geneontology.org/job/geneontology/job/pipeline/job/issue-183-code-too-large/6/execution/node/22/log/): Yep, it works. We see the echo's printed out in Jenkins console log right before the expected `Only master can touch that target` error.

So @kltm, it looks like "methodizing" code outside of the `pipeline` block will get us past the `Method code too large` error.

**Comment by lpalbou** [comment]
Just a small note: it could be good to not group together in a same sub-script the time consuming processes and the quick ones (especially if they can fail). Decoupling long vs small jobs would help to restart from specific stage and avoid losing precious time

**Comment by kltm** [comment]
This has started occurring again on _just_ `release`--`snapshot` and all others are fine.

**Comment by kltm** [comment]
Test run moving forward on `release` branch.

**Comment by kltm** [comment]
Seems good for the moment.

**Comment by kltm** [comment]
Noting alternate issue: https://issues.jenkins.io/browse/JENKINS-37984
