### ISSUE TITLE
Released GAF files have incorrect format

### ISSUE THREAD

**Issue by alexsign** [geneontology/pipeline#198]
Latest release GAF files in 
ftp://ftp.geneontology.org/pub/go/gene-associations
!gaf-version: 2.1 - is missing from the header

**Comment by dougli1sqrd** [comment]
Ah interesting. I'll take a look. Not sure what the problem is directly at the moment. But I bet it's somewhere new in the writer where we set the version between 2.1 vs 2.2 GAF and something got tangled?

**Comment by kltm** [comment]
When we figure out what is going on, we'll need to update the errata: https://github.com/geneontology/go-site/tree/master/releases/2020-07-16 
This will (naturally) be a blocking issue for the next release (tagging @pgaudet ).

**Comment by kltm** [comment]
This is now looking good on `master`. We'll check again once we have a `snapshot`.

**Comment by pgaudet** [comment]
Looks OK in http://skyhook.berkeleybop.org/release/annotations/
But I dont know if we have a test for the ftp ? 

This is the header from skyhook: 

> !gaf-version: 2.1
!
!Generated by GO Central
!
!Date Generated by GOC: 2020-08-01
!
!Header from source association file:
!=================================
!
!Generated by GO Central
!
!Date Generated by GOC: 2020-08-01
!
!Header from zfin source association file:
!=================================
!gaf_version: 2.1
!Version: 2.226
!Date: 2020/07/31
!From: ZFIN (zfin.org)
!
!=================================
!
!Header copied from paint_zfin_valid.gaf
!=================================
!Created on Wed Jul 29 13:29:42 2020.
!PANTHER version: v.15.0.
!GO version: 2020-07-16.


Thanks, Pascale

**Comment by kltm** [comment]
@dougli1sqrd That header looks correct to me. You?

**Comment by dougli1sqrd** [comment]
Yeah that's the correct one!

**Comment by pgaudet** [comment]
@alexsign Can this be closed ?

**Comment by alexsign** [comment]
@pgaudet yes, please

**Comment by pgaudet** [comment]
thanks
