### ISSUE TITLE
Jenkinsfile should set a variable for the URL of the go.json ontology used by ontobio during the Mega-make step

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/pipeline#200]
This is essentially a special case of https://github.com/geneontology/pipeline/issues/27

When the Mega-make stage runs, it invokes the go-site pipeline Makefile which runs ontobio to filter and process upstream GAF files from the groups, outputting reports and validated versions of the upstream data.

This ontobio validation and reporting process needs the go.json ontology. By default this is grabbed from the latest snapshot pipeline run. But during any given pipeline run we *actually* want the go.json *just built* by that pipeline run, earlier on. This resource will be on skyhook.

We can set a variable with a URL to the skyhook location where the ontology will be placed by the ontology build stage and pass that into the Makefile.
The Makefile will also need to make sure that that variable can be overridden from the environment (usually with `?=`).

This should be done for master, snapshot, and release.

**Comment by kltm** [comment]
@pgaudet Now starting testing.

**Comment by dustine32** [comment]
@pgaudet Just tested the release candidate for this issue similar to what I did in https://github.com/geneontology/pipeline/issues/209#issuecomment-739102824. I skipped `goa_uniprot_all` since I don't think it gets the validation anyway:
```
wget -r -l1 -nd --no-parent -P gaf_files/ -A "gaf.gz" http://skyhook.berkeleybop.org/release/annotations/
wget http://skyhook.berkeleybop.org/release/ontology/go-basic.obo
grep alt_id go-basic.obo | cut -d" " -f2 > list_of_alt_ids
cut -f5 gaf_files/*.gaf > all.gaf.GOterms
grep -f list_of_alt_ids all.gaf.GOterms > gaf_alt_ids
wc -l gaf_alt_ids
0
```
No alt IDs were used in any of the GAFs including `goa_uniprot_all_noiea.gaf` so this is fixed.

**Comment by pgaudet** [comment]
Can we close this then ?

**Comment by kltm** [comment]
@dougli1sqrd @dustine32 We're good here now I believe?

**Comment by dustine32** [comment]
@kltm As far as I can see the problem's been fixed.

**Comment by kltm** [comment]
@dougli1sqrd Opened this, but I think I'll go ahead and close. Please re-open if there are issues.
