### ISSUE TITLE
issue-204-new-species-set is failing due to a bug in the gpad parser and ontobio-parse-assocs script in ontobio

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/pipeline#205]
In the post filter step we use the gpad parser in `ontobio-parse-assocs`. In the gpad parser, raw taxon `Curie` objects were being added to the reports container that keeps track of messages from parsing errors/warnings. When these messages are converted into a JSON file, the `Curie` object cannot be converted into json by default, so that is the source of the error.

The fix is to just sanitize the input coming in to the reports by ensuring we turn all Curie objects into a string before adding it to the report.

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/479 Should address this.

**Comment by kltm** [comment]
Great--I'll start this trial again once the release is clear.

**Comment by kltm** [comment]
Can we just fold this into #204?
