### ISSUE TITLE
Add requirements.txt, or other version info for software that is being run in a Pipeline run

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/pipeline#208]
The Pipeline has a `metadata` directory that has the metadata files that were used to create the pipeline run.

Of interest is what software versions we are running during the pipeline. Like, which go-site we are pointing to and which ontobio version we are pointing to, perhaps the output of `pip freeze` could be fruitful.

**Comment by kltm** [comment]
Is this not covered by the use of docker images? As well, different docker images may be running at different point--there may not be a single runtime set.

**Comment by dougli1sqrd** [comment]
I just found myself trying to prove what ontobio version was running on a given day, but I don't know that I can do that, except to assume that whatever I see in the historic git requirements.txt is correct.

**Comment by kltm** [comment]
A GH tree tag would be sufficient for our purposes in reproducibility.

**Comment by kltm** [comment]
Looking at this, I've added extra output to the mega-make, but believe most of this stuff is discoverable after the fact now from the docker images that almost everything runs in now.

**Comment by kltm** [comment]
Good enough for now, I believe.
