### ISSUE TITLE
Add Rfam2GO source file

### ISSUE THREAD

**Issue by pgaudet** [geneontology/pipeline#210]
hello, 

We display Rfam annotations, it would be nice to show the mapping in the release, with the others: http://snapshot.geneontology.org/ontology/external2go/index.html

The source is here: 
http://ftp.ebi.ac.uk/pub/databases/Rfam/CURRENT/rfam2go/

We should load this like we load InterPro and others 

@kltm @cmungall 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet @balhoff 
I'm trying to remember how we do this. We are talking about the file that becomes http://snapshot.geneontology.org/ontology/external2go/rfam2go , correct?

If so, this is actually a `go-ontology` issue: http://snapshot.geneontology.org/ontology/external2go/index.htmlhttps://github.com/geneontology/go-ontology/blob/94768b8585b11357c47a91ec67534878336e0223/src/ontology/Makefile#L528

So, I guess I'm trying to figure out what is different here...

**Comment by cmungall** [comment]
It is downloaded here:

https://github.com/geneontology/go-ontology/blob/94768b8585b11357c47a91ec67534878336e0223/src/ontology/Makefile#L515-L528

https://github.com/geneontology/go-ontology/blob/94768b8585b11357c47a91ec67534878336e0223/src/ontology/Makefile#L113

**Comment by pgaudet** [comment]
OK, sorry I has missed it. 

Thanks ! 

Pascale
