### ISSUE TITLE
Reinstate ZFIN sanity checks once they have been imported or purge extra IBAs upstream

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#217]
Currently, the pipelien fails on sanity checks with

```
18:30:47  ERROR:sanity:Severe reduction of product for: zfin
```
Looking at the current `snapshot` attempt and last `release`, we can see that the upstream ZFIN source has many more annotations coming in now:
```
sjcarbon@moiraine:/tmp$:( wc -l curr/* snap/*
   257403 curr/zfin.gaf
   314410 curr/zfin-src.gaf
   179872 curr/zfin_valid.gaf
   292432 snap/zfin.gaf
   594608 snap/zfin-src.gaf
   214886 snap/zfin_valid.gaf
```
Digging in:
```
sjcarbon@moiraine:/tmp$:) cat curr/zfin-src.gaf | grep -v '^!' |  cut -f 7 | sort | uniq -c
 132251 IBA
     94 IC
   4143 IDA
 141920 IEA
    154 IEP
   5034 IGI
  17150 IMP
   1010 IPI
     12 ISO
   6763 ISS
    127 NAS
   5677 ND
     70 TAS
sjcarbon@moiraine:/tmp$:) cat snap/zfin-src.gaf | grep -v '^!' |  cut -f 7 | sort | uniq -c
 377514 IBA
    117 IC
   4576 IDA
 167116 IEA
    162 IEP
   5079 IGI
  18058 IMP
   1208 IPI
     12 ISO
  14907 ISS
    127 NAS
   5655 ND
     72 TAS
```
It does indeed seem to be an upstream IBA issue.
```
sjcarbon@moiraine:/tmp$:) cat curr/zfin-src.gaf | grep -v '^!' |  grep [[:space:]]IBA[[:space:]] | cut -f 14 | sort | uniq -c | head -1
  25777 20170228
sjcarbon@moiraine:/tmp$:) cat snap/zfin-src.gaf | grep -v '^!' |  grep [[:space:]]IBA[[:space:]] | cut -f 14 | sort | uniq -c | head -1
  68756 20170228
```
That means in the last few weeks, you accumulated ~40k IBAs dated 20170228.
Looking at
```
sjcarbon@moiraine:/tmp$:) cat snap/zfin-src.gaf | grep -v '^!' |  grep [[:space:]]IBA[[:space:]] | grep 20170228 | sort | uniq -c | cut -f 1 | sort | uniq -c
   7900       1 ZFIN
   8819       2 ZFIN
  14406       3 ZFIN
```
There is a situation where many IBA lines (in this example 20170228) are duplicate or triplicate.

From @sierra-moxon , it looks like there was a one-off hiccup during a GOA load process, that led to duplications leaking into their system.

From the GO side, since we want to push forward quickly with a fix to get ready for our March GAF 2.2 release, we will likely:
- [ ] suppress the ZFIN trigger in the sanity checks (caused by the 1/2+ reduction we're seeing now when compared to src due to duplicate IBA filtering)

Other options include
- pointing our ZFIN upstream source to a previous GO release until a ZFIN fix is found
- waiting out the issue and using the IBA-free ZFIN data once they have been fully 'imported" into GO Central for curation

Closing this ticket would be reverting ZFIN to a good upstream with all sanity checks either turned back on on or re-tuned for ZFIN.

Tagging @sierra-moxon @dustine32 @dougli1sqrd @sabrinatoro @vanaukenk @pgaudet

**Comment by sabrinatoro** [comment]
@kltm 
The issues in the ZFIN GAF have been resolved (all the annotations coming from our GOA GAF load, including IBA, were duplicated).
In addition, we have updated the GAF to the latest 2.2 format. Note that I have updated the zfin.yaml with the url to get this latest file

**Comment by kltm** [comment]
Related: https://github.com/geneontology/go-site/pull/1647
