### ISSUE TITLE
current & release.geneontology.org as https endpoints

### ISSUE THREAD

**Issue by lpalbou** [geneontology/pipeline#218]
Most resources in GO are not https - which cause a trail of issues -. This ticket is to enable https at least on the current & release.geneontology.org. This will only have benefits and is easy to do with AWS / Cert manager.

As a reminder, https site (e.g. alliance) can not fetch data from non https endpoints. So GO components can not work in the alliance without us enabling https. The same issue will arise when integrating the go cam widget in the alliance, as barista is not https. @cmungall

**Comment by kltm** [comment]
Previous open at https://github.com/geneontology/go-site/issues/1503
