### ISSUE TITLE
Annotations missing from Noctua gpad (SGD)

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/pipeline#229]
SGD cannot find any annotations made in Noctua post 20210319 in the output gpad, eg gomodel:60418ffa00002093 made (and marked production) on 20210331: https://github.com/geneontology/noctua-models/blob/master/models/60418ffa00002093.ttl

We looked in http://snapshot.geneontology.org/products/annotations/noctua_sgd.gpad.gz, and @kltm checked  http://snapshot.geneontology.org/products/annotations/noctua_sgd-src.gpad.gz. 

Snapshot looks like it's from 2021-04-04: http://snapshot.geneontology.org/summary.txt

Tagging @dustine32 @balhoff

**Comment by suzialeksander** [comment]
From @dustine32: 
>it looks like the example model 60418ffa00002093.ttl wasn’t auto-committed to noctua-models until 4/5 (after the 4/4 pipeline would have run the Noctua GPAD step) https://github.com/geneontology/noctua-models/commits/master/models/60418ffa00002093.ttl

**Comment by kltm** [comment]
For now, duping onto #172
