### ISSUE TITLE
S3 uploader needs to support multipart

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#23]
The naive uploader I wrote to take over for `s3cmd` (which had a borked mimetype) does not use multipart uploads, causing an `EnitityTooLarge` error when attempting to upload some of our larger files to S3. To fix this, we'll just go ahead and make the script use multipart ubiquitously.

@dougli1sqrd is taking first crack at this.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/548
