### ISSUE TITLE
Ontobio dependency fails to install with older version of pip in the pipeline

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/pipeline#232]
The pipeline has encountered an error when trying to install ontobio, even though nothing about the versions or immediate dependencies have changed.

Earlier I had encountered issues with pip suddenly unable to install dependencies, and there the error message suggested to upgrade pip:

```
Collecting cryptography>=2.0 (from SecretStorage>=3.2; sys_platform == "linux"->keyring>=15.1->twine->ontobio==2.6.3)
  Downloading https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz (546kB)
    100% |████████████████████████████████| 552kB 89.1MB/s 
    Complete output from command python setup.py egg_info:
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mkgtddld/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mkgtddld/cryptography/
```
Upgrading pip with `pip install -U pip` in my virtual environment solved this.

As well, I ran into a similar issue as the pipeline locally where it failed to install the pyshex dependency, and I upgraded pip after my experience with the above error, which worked. I was working on a newer version of ontobio, I was local (not in a docker) and the pipeline had not experienced issues as of yet installing pyshex, so I considered it a problem localized to me.

So when this showed up I knew to upgrade pip.

@kltm was able to reproduce the bug in the `dev-base` docker image used in the pipeline, and upgrading pip did indeed fix it.

Pip should be upgraded in the docker image to avoid this.

**Comment by kltm** [comment]
Updated image now being used. This can be closed on any successful run.

**Comment by kltm** [comment]
@pgaudet Just tagging you to the ticket I mentioned this morning (here).
