### ISSUE TITLE
In some circumstances, when converting noctua gpad to gaf, a sizable number of evidence codes are lost

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#240]
In some circumstances, when converting noctua gpad to gaf, a sizable number of evidence codes are lost. Specifically, when examining and comparing the annotations for Xenbase at

http://skyhook.berkeleybop.org/issue-go-site-1434-add-xenbase/products/annotations/noctua_xenbase.gpad.gz
http://skyhook.berkeleybop.org/issue-go-site-1434-add-xenbase/products/annotations/noctua_xenbase_valid.gaf.gz

Looking at the evidence codes (comment lines pre-filtered):

```
sjcarbon@moiraine:/tmp$:) cat noctua_xenbase.gpad | grep -v ^! | cut -f 6 | sort | uniq -c
      2 ECO:0000250
     14 ECO:0000266
      1 ECO:0000270
      1 ECO:0000289
      5 ECO:0000303
     16 ECO:0000304
     31 ECO:0000314
     51 ECO:0000315
      4 ECO:0000318
      1 ECO:0000353
      3 ECO:0001149
      1 ECO:0001174
      1 ECO:0001175
      2 ECO:0001187
      1 ECO:0001838
      4 ECO:0005601
      2 ECO:0005648
      5 ECO:0005667
      2 ECO:0005801
      6 ECO:0005804
      2 ECO:0006030
      3 ECO:0006050
    309 ECO:0006051
     34 ECO:0006063
      2 ECO:0006093
      1 ECO:0006101
      9 ECO:0007089
      4 ECO:0007118
      5 ECO:0007719
      2 ECO:0007726
sjcarbon@moiraine:/tmp$:) cat noctua_xenbase_valid.gaf | grep -v ^! | cut -f 7 | sort | uniq -c
    399 
     31 IDA
      1 IEP
     51 IMP
      1 IPI
     14 ISO
      2 ISS
      5 NAS
     16 TAS
```

I'm unsure of the severity here as I do not believe that this file is used anywhere and only seems to appear when attempting noctua merges. That said, the loss does seem to map to unexpectedly low annotations in some cases (e.g. https://github.com/geneontology/go-site/issues/1434).

This seems to be occurring uniformly, see: http://skyhook.berkeleybop.org/issue-noctua-models-170-zfin-import-test/products/annotations/noctua_zfin_valid.gaf.gz

I'm wondering if maybe this is a product of missing an ontology or context file for that step that normally occurs (possibly similar in nature to the taxon:0 issue: https://github.com/geneontology/pipeline/issues/239).

Tagging @dustine32 and @sierra-moxon

**Comment by kltm** [comment]
Also tagging @vanaukenk

**Comment by malcolmfisher103** [comment]
Thanks for that breakdown, It seems to mostly be morpholino evidence (ECO:0006051) and a few other ECO codes that I would have expected to resolve to IMP not doing so.

**Comment by kltm** [comment]
Dupe with https://github.com/geneontology/pipeline/issues/283?
