### ISSUE TITLE
Noctua gpad snapshots not updated since 6-6?

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/pipeline#241]
At least for MGIs;

**Comment by kltm** [comment]
@hdrabkin This is due to the `snapshot` pipeline not having a completion recently. This likely originates with: https://github.com/geneontology/go-site/issues/1382#issuecomment-860898674 .
It is being re-run/started now.

**Comment by kltm** [comment]
Assuming that this is no longer an issue. Please reopen if there is still a problem.

**Comment by hdrabkin** [comment]
PR:P35639-1
PR:A0A2R8VHR8-1
PR:000050563

Still not in Noctua but are in mgi.gpi file.
