### ISSUE TITLE
Set new --ontojournal option in Make Noctua GPAD stage

### ISSUE THREAD

**Issue by dustine32** [geneontology/pipeline#249]
With the merge of https://github.com/geneontology/minerva/pull/429, the minerva `--lego-to-gpad-sparql` command in the  Jenkinsfile will need to be updated to set the now required `--ontojournal` option.
https://github.com/geneontology/pipeline/blob/e18efbcdd80a7d69328bbbf99258edb620b53283/Jenkinsfile#L461

This new option will specify the local file path where `blazegraph-go-lego-reacto-neo.jnl` exists. If this file doesn't exist in that location, which it never will/should in a clean Jenkins run, minerva will automatically download the file from here:
http://skyhook.berkeleybop.org/issue-35-neo-test/products/blazegraph/blazegraph-go-lego-reacto-neo.jnl.gz

The downloaded file will then be saved in the `--ontojournal`-specified path.

We will use this ticket to coordinate the minerva code change merges to `minerva/dev` and `minerva/master` with the pipeline branches to avoid any unnecessary Jenkins failures.

First up is to merge https://github.com/geneontology/minerva/pull/429 and run `pipeline/issue-238-wormbase-test-pipeline`.

Tagging @kltm @balhoff

**Comment by kltm** [comment]
I'm seeing `--ontojournal` in current `snapshot`, so I guess we did this at some point.
