### ISSUE TITLE
Ensure that new JaponicusDB resource functions properly in the pipeline

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#252]
JaponicusDB is now being added to the metadata for GO. See:

https://github.com/geneontology/go-site/pull/1747
https://github.com/geneontology/go-site/pull/1725

Make sure that it can properly make its way through the pipeline.

**Comment by kltm** [comment]
`snapshot`  pipeline failure with:
```
16:51:46  + python3 ./scripts/downloads-page-gen.py -v --report ./combined.report.json --date 2021-10-20 --inject ./scripts/downloads-page-template.html
16:51:46  INFO:downloads-page:Verbose: on
16:51:46  INFO:downloads-page:Will operate on: ./combined.report.json
16:51:46  INFO:downloads-page:Will use date: 2021-10-20
16:51:46  INFO:downloads-page:Will inject into: ./scripts/downloads-page-template.html
16:51:49  Traceback (most recent call last):
16:51:49    File "./scripts/downloads-page-gen.py", line 114, in <module>
16:51:49      main()
16:51:49    File "./scripts/downloads-page-gen.py", line 97, in main
16:51:49      if smap[scode]:
16:51:49  KeyError: 'Sjap'
```

**Comment by kltm** [comment]
@pgaudet Do we want this in the release we're trying for now (October), or is this more a November thing?

**Comment by kltm** [comment]
To get it "completely" in, we'd also need to add it to the AmiGO loader profile. Otherwise, it would go through the pipeline (collecting stats, etc.), but not appear in AmiGO.

**Comment by kltm** [comment]
I have now heard that we can move ahead with fully adding this.
Things that need to be taken care of:
- [ ] update metadata
- [ ] update stats code
- [ ] update stats dropdown
- [ ] add to amigo metadata

**Comment by pgaudet** [comment]
@kltm Should this be done in the release that started yesterday?

**Comment by kltm** [comment]
@pgaudet See: https://github.com/geneontology/pipeline/issues/252#issuecomment-959434124
We may have gotten a little ahead of ourselves here, as https://github.com/geneontology/go-ontology/issues/22362 has apparently gotten nowhere, but it still puts us in a better position than we were last release. Could you follow up on that one at an ontology call?

**Comment by pgaudet** [comment]
Sure ok - just that an [earlier comment](https://github.com/geneontology/pipeline/issues/252#issuecomment-948142315) said this was a task for the Nov release.

**Comment by kltm** [comment]
@pgaudet That was more about how we were in an "in between" state: initially, we had the file going through QC and in downloads, but not appearing in AmiGO; with this release, the annotations should be in AmiGO, but may not be accessed with the species filter easily (geneontology/go-ontology#22362, naturally, available by other filters). If we finalize this release, I think it's an improvement (i.e. better than the last release), but there are a couple of edges to sand off still.

**Comment by kltm** [comment]
@pgaudet I believe that this is actually completed and everything works as intended for the data we have. (The go ontology issue above was not really an issue--the metadata was just farther down given the number of annotations we had.)

**Comment by pgaudet** [comment]
@ValWood please let us know if this is not behaving correctly

**Comment by kimrutherford** [comment]
Thanks!  Looks good to me.

The experimental annotations for japonicus are in AmiGO: http://amigo.geneontology.org/amigo/reference/PMID:27059155
and the gene product pages are there: http://amigo.geneontology.org/amigo/gene_product/JaponicusDB:SJAG_01143

I noticed that JaponicusDB is using an incorrect database prefix to link to the gene product pages.  I'll fix that now.

**Comment by ValWood** [comment]
Looks good.

**Comment by ValWood** [comment]
Actually, I notice that the abstract and title is not always populating. See for example PMID:29191091
