### ISSUE TITLE
Pipeline fails with new odk image 1.2.30

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#258]
@balhoff The pipeline now fails with `image 'obolibrary/odkfull:v1.2.30'` from https://github.com/geneontology/pipeline/pull/257.
It seems to be missing `scp`. I might suggest rolling forward all present packages into new images.

**Comment by balhoff** [comment]
Thanks for testing! I'll open an issue at ODK.

**Comment by kltm** [comment]
@balhoff The ontology build stage seems to have passed!
