### ISSUE TITLE
dictyBase (others?) upstream data file not available

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#260]
Normal use of the main GO pipeline (including `snapshot` and `release` pipelines) is currently halted on ftp://ftp.ebi.ac.uk/pub/contrib/goa/dictyBase.gaf.gz, in the metadata, apparently not being available.

Taggin @pgaudet

**Comment by kltm** [comment]
@pgaudet @vanaukenk Noting that this is also causing the NEO pipeline to fail.

**Comment by kltm** [comment]
@pfey03 @rjdodson, would you have any odea what happened to this file and why?

**Comment by vanaukenk** [comment]
@kltm @pfey03 @rjdodson - I was just running our WB Protein2GO parsing script and found that the C. elegans file was not available on the GOA ftp site.
Looking at what is there now for dictyBase, it looks like their source file gaf is not there, either.
I just emailed Alex about the WB file, but am tagging him here, too.  @alexsign

**Comment by alexsign** [comment]
there were multiple different issues with the EBI FTP last week. I'm re-running data unload now and let you know when done.

**Comment by alexsign** [comment]
the files are re-created and uploaded to the EBI FTP now.

**Comment by pfey03** [comment]
Thanks @alexsign

**Comment by kltm** [comment]
A little testing looks good at this end. Thank you!
