### ISSUE TITLE
TAIR upstream data file not available

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#264]
Normal use of the main GO pipeline (including snapshot, releas, and NEO pipelines) is currently halted on tair, in the metadata, apparently not being available. For example

`12:45:14  --2022-01-07 12:45:09--  (try:20)  https://www.arabidopsis.org/download_files/GO_and_PO_Annotations/Gene_Ontology_Annotations/gene_association.tair.gz`

Tagging @pgaudet

**Comment by kltm** [comment]
@tberardini, would you have any idea what happened to this file? I can confirm that from this location at ~3:30pm it is still unavailable.

**Comment by tberardini** [comment]
Hang tight. We are updating SSL certificates. Should be done by tonight. I can send you the file directly, if that will help.

**Comment by kltm** [comment]
@tberadini No problem. From our end this is the third or fourth upstream we've had wander off this week, so I was beginning to wondering if something else might be going on. Things are automated enough that there's not much easily done with a file--waiting little is fine.

**Comment by tberardini** [comment]
2022, the year that doesn't stop giving, and we're only 7 days in.

**Comment by kltm** [comment]
I'm considering hibernation.

**Comment by kltm** [comment]
File appears to be back.

**Comment by tberardini** [comment]
Yup, thank goodness.
