### ISSUE TITLE
Xenbase upstream data file not available

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#266]
The GO pipeline for the NEO build is currently halted on the Xenbase upstream not being available:

```
19:30:27  --2022-01-11 19:30:23--  ftp://ftp.xenbase.org/pub/GenePageReports/xenbase.gpi.gz
19:30:27    (try:20) => ‘mirror/xenbase.gpi.gz.tmp’
19:32:33  Connecting to ftp.xenbase.org (ftp.xenbase.org)|136.159.155.151|:21... failed: Connection timed out.
19:32:33  Giving up.
12:45:14 --2022-01-07 12:45:09-- (try:20) https://www.arabidopsis.org/download_files/GO_and_PO_Annotations/Gene_Ontology_Annotations/gene_association.tair.gz
```

In fact, xenbase.org, the root site, seems to be missing from the internet as well. Registered until 2026, so possibly a server problem at that end?

Tagging @pgaudet @vanaukenk

**Comment by kltm** [comment]
@malcolmfisher103, would you have any idea what happened to this file? I can confirm that from this location at ~10am PT it is still unavailable.

**Comment by malcolmfisher103** [comment]
@kltm
I'm afraid our site was hit with an attack over the weekend and we are in the midst of trying to reinstate our system. All of our FTP products are unavailable on Xenbase.

**Comment by kltm** [comment]
@malcolmfisher103 Ugh, I'm sorry that happened. Thank you for the information.

@vanaukenk This leads to an interesting question: we have no backup products for Xenbase and the GPI here, so the options are to

1) /not/ update; leaving an older version, but Xenbase in
2) update w/o Xenbase; I don't think we want to do this
3) try and figure out if we can extract a Xenbase GPI from our current store, save it, make it available to ourselves, then rerun pointing at that; would take time and 4 might beat us
4) wait until Xenbase is back online

**Comment by malcolmfisher103** [comment]
I have a local copy of the file but it is from the middle of September.

**Comment by kltm** [comment]
@malcolmfisher103 Hm. While that could be useful in a pinch, unless your data has not changed a lot since then, if it goes the way of needing to build around this issue it may in fact be more convenient to create a pseudo-GPI from the data store we are currently running off of. If, for whatever reason, we couldn't do that, having access to that file would be valuable.

**Comment by malcolmfisher103** [comment]
I'll talk to our Devs. They have access to very recent backups, around Christmas, of most of our data so I can see if they have the FTP VMs available. They might also be able to give me an updated ETA on having things back up.

**Comment by malcolmfisher103** [comment]
To follow up my previous post, we can get the GPI file from just before Christmas, which should be up to date. As far as the site being back up, this relies on the cooperation of our hosting institution which is still investigating the breach. I'm told it could be between days to weeks to be fully back up and running. Sorry to be so imprecise.

**Comment by kltm** [comment]
@malcolmfisher103 No worries--I totally understand how these things can go.
From a GO perspective, if you can get me that file somehow (google drive? skype? other?), I can put that into a public location, aim the metadata at it, and we can continue on until things are more fully resolved at your end.

**Comment by malcolmfisher103** [comment]
I'll send it as soon as our team has managed to mount the FTP VM backup and get me a copy, that may not be until tomorrow as they are having to mount them on their home systems.
________________________________

**Comment by malcolmfisher103** [comment]
[xenbase.gpi.gz](https://github.com/geneontology/pipeline/files/7862197/xenbase.gpi.gz)
@kltm 
This is our version from the most recent backup. While it is nearly a month old most of the intervening time was holidays, so I doubt we were creating many new gene entities.

**Comment by kltm** [comment]
@malcolmfisher103 Great, thank you! We've updated and our build now seems to be proceeding.

@vanaukenk Assuming the build goes through, everything is fine, etc., this would put us a little behind schedule for the restart cycle, but not terribly so. I'd estimate about a half hour behind where we usually are. Unless I hear otherwise, you have some other concern or thought, or something goes wrong, I'll assume that we'll still go ahead.

**Comment by kltm** [comment]
@pgaudet That's a temp file.

**Comment by malcolmfisher103** [comment]
@kltm @pgaudet 
We are now up and running on our own hardware again so the original address for the gpi file (ftp://ftp.xenbase.org/pub/GenePageReports/xenbase.gpi.gz) should be working again.

**Comment by kltm** [comment]
@pgaudet This is a GPI file, for NEO, and not the main pipeline (at this point). It has been reverted and should be out with the next NEO update.
