### ISSUE TITLE
Look into ceasing production of Zenodo reference releases

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#269]
Look into ceasing production of Zenodo reference releases: reference releases, due to their indirection via bdbags, are a little harder to maintain (see a few tickets around missed) and can potentially suffer from bit rot. I believe that not producing these can be a significant time saver over time and that they are not useful (and should not be generally used anyways).

If confirmed, this ticket would convert into halting the production of the reference release on `snapshot` and `release`.

**Comment by kltm** [comment]
Examples of reference issues would be #89 #99 #189

**Comment by kltm** [comment]
First look at this: zenodo archive vs reference: zenodo citations 16 to 0

**Comment by kltm** [comment]
Well, after trying some random DOIs (both base and version) with Google, it looks like that is not a great way to get information--nothing really useful turned up for archive or reference.

**Comment by kltm** [comment]
As discussed, this is slated for shutdown.

**Comment by kltm** [comment]
Testing now queued onto `master`.

**Comment by kltm** [comment]
Update occurred. Will close on successful `snapshot`.

**Comment by suzialeksander** [comment]
when this clears, what does this mean as far as documentation I need to change on the website? Is this removing the whole zenodo process including the doi, or something else ??

**Comment by kltm** [comment]
@suzialeksander Poking around, the only change might be here
http://geneontology.org/docs/downloads/
removing
"Interested in a smaller or more flexible DOI versioned bundles? Holey (reference) BDBag available at [Zenodo - record 1205159](https://doi.org/10.5281/zenodo.1205159)"
We will still be getting DOIs and depositing in Zenodo (for the time being), but we are creating one less archive--the "reference" archive. Largely, we do not refer to it or have already removed documentation to it.

**Comment by kltm** [comment]
@suzialeksander Frankly, as it's already functionally deprecated, that can be removed now. We'll add something to the release notes when it goes out.

**Comment by kltm** [comment]
Proved.
