### ISSUE TITLE
Typo in the mgi-prediction file?

### ISSUE THREAD

**Issue by ukemi** [geneontology/pipeline#276]
While importing the annotations from the mgi-prediction file, we are having the following annotation kicked out:
MGI     MGI:3642276     Rnf212b         GO:0016925      PMID:21873635   IBA     PANTHER:PTN001099470|SGD:S000004386     P       RING finger protein 212B        UniProtKB:D3Z423|PTN001862305   protein taxon:10090     20170228GOC

It looks like it is derived from a PAINT annotation and somewhere in the pipeline a change had not been propagated correctly. At MGI:
MGI:3642276  Gm10332
MGI:5589964   Rnf212b

Gm10332 is a withdrawn marker and should not have annotations associated with it. So either this annotation should be removed of switched to MGI:5589964 if that is the object that is annotated in the source annotation from PAINT.

**Comment by kltm** [comment]
@balhoff @dustine32 @ukemi 
I just noticed this and wanted to see if it was still active? Within that, is this an issue on the PAINT side of things, or within the pipeline on this side. If on this side, it would be produced then from `owltools` with the `--gaf-prediction-file` flag.

**Comment by ukemi** [comment]
@hdrabkin, is this still getting kicked out?

**Comment by hdrabkin** [comment]
I do not see this annotation in any of our QCs for the load, but also the annotation does not appear in the MGI db. 
We assume it was removed from PAINT so is no longer in the PAINT gaf we load.
