### ISSUE TITLE
 Xenbase upstream data file not available

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#277]
The GO pipeline for the NEO build is currently halted on the Xenbase upstream not being available:

```
10:16:39  --2022-03-10 10:16:39--  ftp://ftp.xenbase.org/pub/GenePageReports/xenbase.gpi.gz
10:16:39    (try:20) => ‘mirror/xenbase.gpi.gz.tmp’
10:19:00  Connecting to ftp.xenbase.org (ftp.xenbase.org)|136.159.155.151|:21... failed: Connection timed out.
10:19:00  Giving up.
10:19:00  
10:19:00  Makefile-gafs:2: recipe for target 'mirror/xenbase.gpi.gz' failed
10:19:00  make: *** [mirror/xenbase.gpi.gz] Error 4
```

@malcolmfisher103, would you have any idea what happened to this file? I can confirm that from this location at ~2pm PT it is still unavailable.

Noting relation to #266

**Comment by malcolmfisher103** [comment]
@kltm I can only access it using https. I'll check with the Devs, we have updated a lot of security things on our new VMs so there may be issues related to that.

**Comment by kltm** [comment]
@malcolmfisher103 No problem, we're happy to update to whatever the correct URL is. We're just going off of the conversation at https://github.com/geneontology/pipeline/issues/266#issuecomment-1058126269 ; if we should have something else in there, let us know.

**Comment by kltm** [comment]
Temporarily switching to https://ftp.xenbase.org/pub/GenePageReports/xenbase.gpi.gz .

**Comment by kltm** [comment]
@malcolmfisher103 Is https://ftp.xenbase.org/pub/GenePageReports/xenbase.gpi.gz the new permanent files for GPI?

**Comment by malcolmfisher103** [comment]
@kltm Yes, that is the new permanent file.

**Comment by malcolmfisher103** [comment]
I still can't see any Xenbase genes in the suggested gene entities in Noctua, is this still blocking the pipeline?
