### ISSUE TITLE
Suppress or remove owltools *-summary.txt files from pipeline reports

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#281]
Given the ongoing confusion around owltools `*-summary.txt` reports, we want to suppress or remove these files from pipeline reports.

The *-summary.txt files are the last remainder of the owltools reports, currently suppressed form getting to the html file, but not fully removed. (https://github.com/geneontology/pipeline/issues/184, from https://github.com/geneontology/go-site/issues/1095). If there is truly no longer any use for these *-summary.txt files, we can either try and prevent their creation or filter them out and prevent them from getting into the final product.

(Also https://github.com/geneontology/go-site/issues/1816)

**Comment by kltm** [comment]
@pgaudet Noting that the following GORULEs reference the summary (and other owltool) files: `[db_species]-summary.txt`. We'll need to update that before going live with a `release` or `snapshot`.

- [ ] GORULE:0000001
- [ ] GORULE:0000003
- [ ] GORULE:0000006
- [ ] GORULE:0000007

**Comment by kltm** [comment]
@pgaudet Would you like this in for the next `release` attempt?
Example output here: http://skyhook.berkeleybop.org/master/reports/

**Comment by pgaudet** [comment]
This looks OK for example for E. coli, however on skyhook some species are missing like CGD; is that expected? 


Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet For those sample runs, many (most) species/resources are missing so we can run it faster. The important thing there is to note what files are produced for the represented resources.

**Comment by kltm** [comment]
Talking to @pgaudet , we'll go ahead with the release with this new setup and will circle back around to cleaning any documentation later on (i.e. https://github.com/geneontology/pipeline/issues/281#issuecomment-1104444179 and https://github.com/geneontology/go-site/issues/1842).

**Comment by kltm** [comment]
No longer available. Closing.
