### ISSUE TITLE
Revert changes for pinned uberon version once uberon is fixed

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#290]
Once the most up-to-date uberon is no longer causing issues for the GO, we'll want to revert our changes that lock it to http://purl.obolibrary.org/obo/uberon/releases/2022-05-17/uberon-basic.owl .

This would be all pipelines, including release, snapshot, master, and go-ontology-dev.

See https://github.com/geneontology/go-ontology/issues/23468

Tagging @pgaudet @balhoff

**Comment by balhoff** [comment]
@kltm done for go-ontology: https://github.com/geneontology/go-ontology/pull/23897

**Comment by kltm** [comment]
Can be closed once any pipeline with the reversion passes.
