### ISSUE TITLE
Slow and unstable downloads from EBI upstreams increasing pipeline failures

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#305]
Many downloads are slow to the point of a few megabytes taking hours. Figure out the source/reason and fix. More details to come.

- [x] reinstate `go-ontology-dev`
- [x] Get EBI downloads near their original speed

**Comment by kltm** [comment]
Going through the logs, we seem to have the following slow downloads:
- http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl => 13h, 6h
- https://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gaf.gz => 10hr

Trying locally, chebi.owl seems to be fine. goa_uniprot_all.gaf.gz is very very slow locally. Interestingly, for goa_uniprot_all.gaf.gz, switching to FTP gives me very fast (normal) speeds.

Looking through the logs, goa_uniprot_all.gaf.gz seems to have been getting worse since around the 14th; chebi.owl since the 25th.

**Comment by kltm** [comment]
Testing again, I can get good times for goa_uniprot_all.gaf.gz by switching to http _or_ ftp, just not https.
That would explain why we took a dive since https://github.com/geneontology/go-site/pull/1914/files .

@cmungall @balhoff Putting chebi being slow to the side for a moment, this seems to be a fundamental issue with EBI's https service (as opposed to http or ftp). If you're getting similar results (I've tried "locally" and at LBL), rather than waiting for an upstream resolution, I'd just as soon switch

https://github.com/geneontology/go-ontology/pull/24202/files
https://github.com/geneontology/go-site/pull/1914/files
etc.

over to http so we can get things ticking over again and revisit later.

**Comment by kltm** [comment]
Basically, for the same file, we'll get different download speeds depending on the schema. For example

https://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl ~ 4.5KB/s
http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl ~ 15.0MB/s
ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl ~ 20.0MB/s

The difference between FTP and HTTP is not a lot and could probably be accounted for in a few different ways, the HTTPS download is remarkably slower.

**Comment by kltm** [comment]
@alexsign opened a ticket on our behalf and soon after the speed issue seems to have resolved for all the previously slow URLs that I've tested. Thank you!

**Comment by kltm** [comment]
@alexsign Unfortunately, after a short break, the very slow download speeds have started again.

**Comment by kltm** [comment]
@alexsign Doing some quick testing from a single site:
https://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl ~ 424KB/s (~26m)
http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl ~ 422B/s (~27m)
ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl ~ 9.0MB/s (~70s)
It currently appears that http and https now have the same (slow) download speeds, while ftp is at least an order of magnitude faster.

**Comment by alexsign** [comment]
@kltm sorry for delay on this. The HTTPS download speed should improve now. Can you please test it and let me know.

**Comment by kltm** [comment]
@alexsign Cheers! It looks like we just missed the window with out current build; our next full build cycle will start tomorrow at midnight, so we'll get the results over the weekend. I've made a note to check in on them.
Thank you for all of your help on this.

**Comment by kltm** [comment]
@alexsign Doing some testing locally and seeing the current load status, the numbers are completely consistent with https://github.com/geneontology/pipeline/issues/305#issuecomment-1303903774 ; basically, http and https still seem to be extremely slow and ftp is still relatively very very very fast.

**Comment by alexsign** [comment]
@kltm I sent your feedback to the EBI infrastructure team. Hopefully, they'll figure it out eventually.

**Comment by alexsign** [comment]
@kltm EBI infrastructure team made changes again. Please test when convenient.

**Comment by kltm** [comment]
@alexsign Previous runtime for downloads: 10h 33min; current runtime:  22min 59s. A huge improvement! Thank you for running this back and forth for us.

**Comment by kltm** [comment]
@alexsign I hate to do this; maybe there is a person I should be contacting directly? Since about the 25th or 26th of November, downloads are slow again.

**Comment by kltm** [comment]
Looks like things are "fast" again.

**Comment by kltm** [comment]
@alexsign Whoops--my bad. Checking in on this, it is still an ongoing issue, with downloads for our main pipeline runs taking more than ten (10)  hours.

**Comment by kltm** [comment]
All EBI download resources
```
grep -r "ftp.ebi.ac.uk" ~/local/src/git/go-site/metadata/datasets/ | grep -oh "https:.*"
```

**Comment by kltm** [comment]
Getting all non-ontology EBI resources:
`grep -r "ftp.ebi.ac.uk" ~/local/src/git/go-site/metadata/datasets/ | grep -oh "https:.*" > /tmp/files.txt && sed -e 's/https/ftp/g' /tmp/files.txt > /tmp/files.txt.changed && wget -i /tmp/files.txt.changed`

**Comment by pgaudet** [comment]
Also, can you download the compressed file?

**Comment by kltm** [comment]
Just some current stats:

| file | thru | eta |
|------|--------|------|
| http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl.gz | 420KB/s | ~100s |
| http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl | 428KB/s | ~1600s |
| ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl.gz | 9.0MB/s | ~6s |
| ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl | 7.17MB/s | ~90s |
| https://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl.gz | 432KB/s | ~100s |
| https://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl | 432KB/s | ~1600s |

Noting current stats from local machine. I'm not sure about switching over generally to compressed ontology files--that might end up being a bit fiddly or take us to retool with catalogs (i.e. https://github.com/geneontology/pipeline/issues/27#issuecomment-499615634), but it's worth keeping in mind.

**Comment by alexsign** [comment]
@kltm I opened another ticket with EBI infrastructure team. Hopefully, it will be more successful than one before.

**Comment by kltm** [comment]
@pgaudet We've had the second case in a week where either the EBI server or connection is unstable and we lose a run; like:
```
00:03:19  Download of https://ftp.ebi.ac.uk/pub/databases/GO/goa/CHICKEN/goa_chicken_isoform.gaf.gz failed: Unable to establish SSL connection.
```
I think I'm ready to implement a local cache/mirror to support our runs so that we can at least deal with late-stage errors. @cmungall Do you see any problems with this? For the moment it would be a GO-only resource.

**Comment by kltm** [comment]
Noting that grabbing all EBI files, using FTP, takes:
```
Total wall clock time: 39m 53s
Downloaded: 83 files, 38G in 37m 32s (17.2 MB/s)
```
Which is a win over the 12+ hours we're currently at.

The upload from local was `real 50m26.029s`.

```
time s3cmd -c ~/SECRET_CRED --mime-type=text/plain put /tmp/foo/* s3://go-mirror

```

So let's say one and a half hours per mirror attempt.
Pulling from our self-made mirror, we have:
```
Total wall clock time: 13m 29s
Downloaded: 83 files, 38G in 13m 12s (48.8 MB/s)
```
This means that we're doing 3x speed over the old EBI FTP and likely have better stability.
I'd propose that we either 1) switch back to the old EBI FTP or 2) start the process of running off our own mirror.
Tagging @cmungall @pgaudet .

**Comment by kltm** [comment]
I'd also not that we could front this with LBL Cloudflare for free, which might be a fun experiment :)

**Comment by kltm** [comment]
Currently looking at using pipeline branch `goa-copy-to-mirror` to interact with `mirror.geneontology.io`.

**Comment by kltm** [comment]
Currently running a full mirror build test.

**Comment by kltm** [comment]
@dustine32 I'm considering a non-breakign schema change for `datasets.schema.yaml` in the GO metadata, adding `mirror_of`. Essentially, I'd like to be able to refer to where we are directly getting the data for the pipeline (`source`) and how we are mirroring `mirror_of` in the same location. Any thoughts?

**Comment by dustine32** [comment]
@kltm Yeah, I think I'm a fan of `mirror_of`. Is this just an extra field initially for information only or does other code need to be changed to use it?

**Comment by kltm** [comment]
This would be an additional field. Only new code--namely my mirroring code--would need to "see" it, and even then only if they cared about mirrors. Everything else could safely ignore it.

**Comment by dustine32** [comment]
Ah, yeah, that sounds good to me!

**Comment by kltm** [comment]
Testing at https://build.geneontology.org/job/geneontology/job/pipeline/job/master/

**Comment by kltm** [comment]
Now testing on main pipeline branches.

**Comment by kltm** [comment]
Moving to `clearing` for testing.

**Comment by kltm** [comment]
Our download phase has gone from 11+h to 15+m. No oddities yet.
