### ISSUE TITLE
Test and merge PANTHER / PAINT 17 into pipeline

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#307]
Aim at metadata provided in https://github.com/geneontology/go-site/issues/1926 and test new PAINT release.
Tagging @dustine32

**Comment by kltm** [comment]
Working branch is `issue-307-panther-17`. Tagging @dustine32 .

**Comment by dustine32** [comment]
@kltm Thanks for creating the branch! I can update the Jenkinsfile for 17.0 following the change pattern we used in https://github.com/geneontology/pipeline/commit/3deaf006b6bf790c591ad19e1c8c5cf092ed905d.

**Comment by kltm** [comment]
@dustine32 That would be lovely--cheers!
I'd crosscheck that GAF list against `snapshot` to make sure changes like xenbase are there.

**Comment by dustine32** [comment]
@kltm Right, I had to add `xenbase` and `japonicusdb` to the GAF list.

**Comment by dustine32** [comment]
Noting that I also had to remove `aspgd` from the GAF list to avoid another instance of #282 in the go-stats report.

**Comment by dustine32** [comment]
@kltm So with the latest [jenkins test run](https://build.geneontology.org/job/geneontology/job/pipeline/job/issue-307-panther-17/4/) it looks like everything worked OK but the last stage "Produce derivatives" reported failure. I can't seem to figure out why exactly. No errors and it looks like all of the steps completed fine. I checked the go-stats [go-annotation-changes.tsv](http://skyhook.berkeleybop.org/issue-307-panther-17/release_stats/go-annotation-changes.tsv) report and the drop in IBAs matches what I was expecting to see (~316,000 IBAs).

If you're fine with this result then I'm ready to schedule the `PANTHER_VERSION` var switchover on the other pipeline branches `master`, `snapshot`, `release` along with the IBA GAF symlink switch on the PAINT FTP server.

**Comment by dustine32** [comment]
@kltm Looks like the "Produce derivatives" stage rerun finally worked. I'm thinking about getting the switch in today for the `snapshot` starting tonight?

**Comment by kltm** [comment]
I think that's right. If you can get the change (directly) into `master`, I'll propagate it up.
