### ISSUE TITLE
Old go.json file getting propagated into new releases

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#310]
Reported by email, the go.json file in the `2023-01-01` release is the same as the one in the `2022-12-04` release. Closing this involves fixing issue origin and updating release notes.

**Comment by kltm** [comment]
Diffing, http://release.geneontology.org/2023-01-01/ontology/go.json and http://release.geneontology.org/2022-12-04/ontology/go.json are the same.

**Comment by kltm** [comment]
Noting that the `2022-11-03` (http://release.geneontology.org/2022-11-03/ontology/go.json) is different. As well, the current snapshot (http://snapshot.geneontology.org/ontology/go.json) is also showing up as different, so this does not seem to be an ongoing issue. As well, I would note that we had ontology build issues between 12-6 and 12-14 through 01-03, so I'm guessing that that is the underlying issue here.
Comparing the `go.obo` files for these two releases, they _are_ different, so that's a little odd.

Looping in @balhoff , looking at the ontology build Makefile, I saw nothing obvious that would cause a "lag" here in the JSON generation. Can you think of a mechanism that might cause that if the regular ontology build is getting disrupted?

**Comment by kltm** [comment]
Slightly lowering severity as I believe this was caused by other disruptions and is unlikely to continue occurring. It might be good to put a diff in the release pipeline to stop a release if certain files are the same.

**Comment by azat-badretdin** [comment]
Just in case, I am the original reporter.

**Comment by kltm** [comment]
I believe that the fixes presented in https://github.com/geneontology/pipeline/issues/311 will most likely prevent further occurrences of this issue. Retrospective release errata has been added to go-site: https://github.com/geneontology/go-site/tree/master/releases/2023-01-01 .
I am going to put this into clearing for another check at next release.

**Comment by kltm** [comment]
@azat-badretdin The data is lock into the release, as it is in the Zenodo archive, and is immutable. The updated file should be available in the next release, with an update to our mutable metadata about the release already updated (above).
For those that need ontology/data changes quickly, we also offer the "snapshot" releases that do not go through the same procedures/qc as the main releases, but might be useful if you need a specific update quickly in this case:
http://snapshot.geneontology.org ; this is usually for internal GO uses.

**Comment by azat-badretdin** [comment]
Thanks!

**Comment by kltm** [comment]
With closing #311 and checking that the current products are different from snapshot (i.e. future release) products, I think we can call this cleared for now.
