### ISSUE TITLE
In some cases, the ontology build gets dirty and uses old artifacts during build

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#311]
We seems to be having some reoccurring issue where the ontology build will get stuck and apparently reuse bad imports or other files that seems to gum up the build works. Clearing workspaces out manually seems to work for this, but we need something automatic.

We could either have a clean command or find a manual way to clear the workspace--the current workspace cleaning build into Jenkins and explicitly called in the pipeline does not seem to be sufficient.

Tagging @balhoff

**Comment by kltm** [comment]
Will try adding additional directory removal into the pipeline.

**Comment by kltm** [comment]
@balhoff Hm, this is actually going to cause some issues as the items created in the docker image are getting out into the workspace, creating some permission oddities. I can probably finesse this by disappearing the whole thing into a tmpfs (like we do elsewhere), but it would mean that we'd having nothing to inspect on the filesystem if we wanted to do after-the-fact triage of issues (like we have elsewhere). 
Before heading down that path, how hard would it be to have a thorough clean command in the ontology build?

**Comment by kltm** [comment]
@balhoff Hm, this is actually going to cause some issues as the items created in the docker image are getting out into the workspace, creating some permission oddities. I can probably finesse this by disappearing the whole thing into a tmpfs (like we do elsewhere), but it would mean that we'd having nothing to inspect on the filesystem if we wanted to do after-the-fact triage of issues (like we have elsewhere). 
Before heading down that path, how hard would it be to have a thorough clean command in the ontology build?

**Comment by balhoff** [comment]
@kltm can you try running this?

`git clean -fx`

**Comment by kltm** [comment]
Okay, the way this is working in Jenkins, I do not seem to be able to bypass _some_ kind of cleanup before the steps in a stage start. This means that once we're in a weird state, no attempts at clean before build can operate before we hit a failure. With this, we basically lose any hope of preserving artifacts as a standard practice.
That said, I'm going to try and add cleaning at the end; at least with this we could easily temporarily turn it off for debugging if needed, rather than relegating everything to a disappearing tmpfs.

Testing with this continuing.

**Comment by kltm** [comment]
From the logs, the "post" cleaning seems to be doing the trick. I think this can be propagated out and regarded as "done" until there is evidence otherwise.
