### ISSUE TITLE
Create strategy for dealing with no large files in CloudFront

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#32]
It turns out that CloudFront has a max file size of 20G:

    https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html
    Maximum file size for HTTP GET, POST, and PUT requests 20 GB

Currently, our largest files are the blazegraph dumps are just over 25GB and returning an error:

```
    HTTP/1.1 403 Forbidden
    X-Cache: Error from cloudfront
```

even though these are fine on skyhook and and S3.

We have a few ways forward.

* search for a way to do this in CF
* carve files up so that they meet the limit
* Drop CF and use a proxy server in front of S3
* ???

**Comment by cmungall** [comment]
I like the idea of CF in theory - but have we tested how much benefit it's bringing us, in terms of reliability and speed of download, for both us and non-US consumers?

FWIW We know already that for whatever reason ontology PURLs do not always resolve (our purl server? CF layer? S3? Network glitches on client, server or inbetween? Java/OWLAPI weirdness?)

We could also split the distribution. I don't really see an advantage of CF for the blazegraph journal? Of course a split would introduce complexity.

**Comment by kltm** [comment]
Personally, I also very much like the practice of CF too--it has made the handling a *lot* easier for me, especially when looking at all of the above. It has been very very nice and I have never had an issue (until now) traceable to a CF failure, as opposed to the many (hiccup-y) failures that I've had with S3. The cost is a different question; I'm not sure if it is literally worth it compared to the upkeep of a small proxy server or serverless conf. But it is so eeaasyy :)

That said, the mission itself is paramount and if CF does not fit it, so be it--I have not the slightest qualm with dancing on it's body.

If we say that "secondary" products are not bundled and archived, I am fine continuing as we have been and giving the secondary products a more transitory location for distribution (e.g. S3 raw, etc.) as they should technically all be easily derivable from our primary products #9 .

**Comment by kltm** [comment]
From talk with @cmungall large secondary artifacts do not need to be within the "core" data bundle and releases.
I will aim to have these instead somewhere nice like a non-CF S3 backed bucket with a redirect over it. We can still use the indexer and just use download.geneontology.io/BRANCH_NAME/products or something.

**Comment by kltm** [comment]
Okay, after some digging and looking at growth (specifically, using the gzipped TTLs as a base of reference they compressed to ~1.7GB for legacy and ~3MB for all current models (inc. SynGO, but not Reactome)), we would expect to be able to continue with compressed blazegraphs and compressed solr indices for some time, making this issue moot for the time being.
Hopefully, by the time we run into this problem more solidly, size limits will be relatively higher across the board.
