### ISSUE TITLE
Document recent pipeline changes

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#320]
We want to modify/update go-archives docs with latest changes (http://geneontology.org/docs/go-archives/)

As well, take a look and make sure that https://wiki.geneontology.org/Release_Pipeline is up to date.

From discussion with @pgaudet

**Comment by kltm** [comment]
This can be continued once the next release is out.

**Comment by kltm** [comment]
From:
```
goa_uniprot_all.gaf.gz
goa_uniprot_all_noiea.gaf.gz
goa_uniprot_all_noiea.gpad.gz
goa_uniprot_all_noiea.gpi.gz
```
to
```
filtered_goa_uniprot_all.gaf.gz
filtered_goa_uniprot_all_noiea.gaf.gz
filtered_goa_uniprot_all_noiea.gpad.gz
filtered_goa_uniprot_all_noiea.gpi.gz
```

**Comment by kltm** [comment]
After a quick read of http://geneontology.org/docs/go-archives/, I can see nothing that needs updating that wasn't unrelated and already broken.

**Comment by kltm** [comment]
Not much really needed to be changed in the Release_pipeline wiki either.

**Comment by pgaudet** [comment]
Done in the May 2023 release
http://release.geneontology.org/2023-05-10/annotations/index.html
