### ISSUE TITLE
Add documentation for MGI upstreams pipeline

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#326]
We want to document the process of taking files from the upstream and producing what MGI will have previously generated.
This is currently documented in great detail here: https://drive.google.com/drive/folders/17O5e3gj_fkbSv2vscEYNIzpCNLIq3fG2 (which is active notes and technical docs for this project).

However, for the long term, we'd like to encode this information in GORULEs and the like.

An initial step could be documenting this under a new GORULE that is taken care of by the new software (and can be added to the current outputs). This can be made more granular as time goes on.

Tagging @sierra-moxon @ukemi @pgaudet

**Comment by kltm** [comment]
@sierra-moxon We can talk about this elsewhere, but there is no need for GORULEs to be part of ontobio, we would just need documentation at https://github.com/geneontology/go-site/tree/master/metadata/rules
Additionally, we could add stanzas to the goa.yaml metadata to indicate where data is coming from.
@pgaudet There can also be more user/external-facing documentation.

**Comment by kltm** [comment]
For the GO_REF angle, there is also geneontology/go-site#2019

**Comment by kltm** [comment]
@pgaudet I think everything we need fir the software side is now part of the GORULEs framework. Is there anything you'd like to have documented before we close this out?

**Comment by pgaudet** [comment]
Hi @kltm 
Yes, @LiNiMGI and I would like to look at this. Specifically: 

 

- [ ] Li will review the documentation to see if this is what was done, 
especially https://docs.google.com/presentation/d/1X2dNR1tp0EnIUjs7X3iMxxzqN230Hb_OkhB02AUXUyQ/edit#slide=id.gd84e6c502f_0_0 (there are 3 slides, presumably only one version was done)
- [ ] create some 'executive' summary of the work
- [ ] move folder to a different location (now in 'Outreach')


Thanks, Pascale

**Comment by sierra-moxon** [comment]
I tried to capture the "preprocess steps" in this diagram -- feel free to use or edit or throw away (it did not take me a long time).  The "green" is the go preprocess pipeline actions. 


![Image](https://github.com/geneontology/pipeline/assets/4561292/e7fe78f9-0545-4dc7-baea-7f52c91b95b8)

**Comment by pgaudet** [comment]
Hi Sierra, 

This looks great! 

A couple of questions: 

- Step 1 on the left: can you specify the source of the RGD and human GAF files? 
- Homology Excludes rules: why do you map to HGNC? Is this what will be in the 'with'? Are we going to have two namespaces for human? 
- 
Thanks, Pascale

**Comment by sierra-moxon** [comment]
Second iteration (many more details) including arrows to indicate how "control" moves between the gopreprocess Makefile and the silver-issue-325-gopreprocess pipeline branch.  Also included is the location of the necessary files that are used to generate the MGI GAF now, and the timing in the pipeline where it writes intermediate files back to skyhook.

Green = silver-issue-325-gopreprocess pipeline
Pink = Makefile in gopreprocess code repo
White = files downloaded
Orange = skyhook

![Image](https://github.com/geneontology/pipeline/assets/4561292/8a4f45ad-8331-4242-ba70-c06eaeca1dbe)

**Comment by sierra-moxon** [comment]
@pgaudet - I have to go to HGNC in order to use the Alliance orthology file as Alliance uses HGNC ids.

**Comment by pgaudet** [comment]
OK, got it ! thanks :)

**Comment by kltm** [comment]
@pgaudet If anything more needs to be done here, please re-open.
