### ISSUE TITLE
Make sure that all MGI annotation products are covered by GO

### ISSUE THREAD

**Issue by ukemi** [geneontology/pipeline#332]
In discussion with @leemdi this morning, we went over all of the MGI products that will no longer be valid once the switchover is made to the GOC. It doesn't make sense for @leemdi to continue to generate annotation files when the source of those files is the GOC. Currently we make the following:

- gene_association.mgi (GAF)---- is already made in the pipeline
- gene_association_pro.mgi (GAF)----- This file is a filtered file that is used by the protein ontology for their mouse load. It is not currently made by the GOC. We will have to work with Darren to resolve this.
- mgi.gpad------ is already made in the pipeline
- 
- annotations w/out NOCUTA or GO_Central (PAINT)
- gene_association_nonoctua.mgi (GAF)---- will become irrelevant because it is used by the GOC for the loads
- gene_association_nonoctua_pro.mgi (GAF)-------- will become irrelevant
- 
- - mgi_nonoctua.gpad--------- will become irrelevant

**Comment by sierra-moxon** [comment]
Hi @ukemi and @kltm - I am not sure what the "definition of done" or deliverables are for this ticket.  Can we clarify in a meeting?

**Comment by ukemi** [comment]
HI Sierra. This ticket list the products that we make available on our web site. The ticket will be done when the GOC creates all the products that are still relevant as indicated above. Once we are happy with the gaf and GPAD that are emitted from the pipeline, there is one additional file that we provide to the people at PRO. It is a filtered file containing all of the isoform annotations. Once we are happy with these, this ticket is closed:
gene_association.mgi (GAF)---- is already made in the pipeline
gene_association_pro.mgi (GAF)----- This file is a filtered file that is used by the protein ontology for their mouse load. It is not currently made by the GOC. We will have to work with Darren to resolve this.
mgi.gpad------ is already made in the pipeline

**Comment by kltm** [comment]
@LiNiMGI @ukemi Can this be closed, or is it being kept open for documentation?

**Comment by pgaudet** [comment]
@LiNiMGI 

Where does this stand?

**Comment by LiNiMGI** [comment]
I think MGI is waiting for the MGI files to be produced in the new pipeline. if all goes well we will close this ticket. thanks, Li

**Comment by ukemi** [comment]
@LiNiMGI 
This one might still need attention:

gene_association_pro.mgi (GAF)----- This file is a filtered file that is used by the protein ontology for their mouse load. It is not currently made by the GOC. We will have to work with Darren to resolve this.

**Comment by LiNiMGI** [comment]
Lori discussed this with Darren and he will mine the data from the GOC-provided annotation files when available. Thanks, Li

**Comment by pgaudet** [comment]
@LiNiMGI 

Is this finished?

**Comment by LiNiMGI** [comment]
yes, we can close it now, thanks!  Li

**Comment by pgaudet** [comment]
Great ! thanks
