### ISSUE TITLE
Suppression of ND Annotations When Other Annotations come in from ISO and IEA loads

### ISSUE THREAD

**Issue by ukemi** [geneontology/pipeline#343]
This came up for a separate ticket at MGI, but I realize that we have to deal with it here.

1. When curators have reviewed the literature and can't find any information about a gene, then make a special annotation to the root node. This annotation is a placeholder that curators use to determine that a gene has been reviewed.
2. If annotations exist from one of the ISO pipelines or an IEA pipeline, then the annotation is retained in MGI but the display is suppressed on the front end (public).
3. If an annotation comes in from the GOA mouse load, then the annotation is removed from the database.
@leemdi, is this correct?

We need to figure out how to deal with this on the GOC end now.

**Comment by sierra-moxon** [comment]
@leemdi - do you remember if this is something you're handling at your end, or if there needs to be additional support on the GO side of the fence for this one?

**Comment by kltm** [comment]
Tagging on @LiNiMGI to follow up.

**Comment by pgaudet** [comment]
This should be covered by gorule-0000048

https://github.com/geneontology/go-site/issues/914

We could consider implementing this as a filter *after* the pipeline is finished.

**Comment by pgaudet** [comment]
@LiNiMGI will check if MGI can do something on their end, until GOC can implement the check.
