### ISSUE TITLE
Test SGD manual annotations exported from Noctua models

### ISSUE THREAD

**Issue by dustine32** [geneontology/pipeline#354]
Similar to #237, add a testing pipeline for SGD manually curated data in the pipeline system for testing.

Tagging @suzialeksander @kltm

**Comment by kltm** [comment]
@dustine32 If this is a "work item", can this be binned into a project?

**Comment by kltm** [comment]
(Binned; change if wrong.)

**Comment by suzialeksander** [comment]
@dustine32 after today's call can you clarify this ticket is still needed, and if it is what you will need to test? Other than the upstream-of-GO changes, nothing at GO should change.  I'll spot check the import during this week's outage, if that's what you meant please reassign this ticket to me

**Comment by dustine32** [comment]
@suzialeksander Yep, you are correct. We shouldn't need this pipeline branch or https://github.com/geneontology/go-site/tree/issue-pipeline-354-sgd-test-pipeline since there won't be any changes to GO metadata.

But one of the nice perks of this test branch is that we get a public URL for the test Noctua GPAD output: http://skyhook.berkeleybop.org/issue-354-sgd-test-pipeline/products/upstream_and_raw_data/noctua_sgd.gpad.gz

**Comment by suzialeksander** [comment]
I don't think there's any work here. SGD annotations will have a final check in the next import but are now "in" Noctua.
