### ISSUE TITLE
Integrate MGI mouse annotations done in P2GO

### ISSUE THREAD

**Issue by pgaudet** [geneontology/pipeline#366]
Hello, 

This was not expected, but it turns out there are 85 annotations in Protein2GO to mouse genes done by MGI curators. These are not in the Noctua/GO central set. Exported annotations by GO are attached. 
This concerns 85 annotations 

Can these be loaded in Noctua? This would be a one-off like the original MGI load.
Once that is done, P2GO can turn them to EXTERNAL annotations. 

@sierra-moxon 
@kltm 
@LiNiMGI 

Putting this in the remainders project but I dont think this is a show stopper, given the small number of annotations. 

[MGI_P2GO_taxon_10090.gpad.txt](https://github.com/geneontology/pipeline/files/14788791/MGI_P2GO_taxon_10090.gpad.txt)

Thanks, Pascale

**Comment by LiNiMGI** [comment]
Thanks Pascale! I will spot checking some of the annotations first.  Li

**Comment by LiNiMGI** [comment]
Karen and I checked some of the annotations, we found some are annotation errors. MGI will check them all and manually delete any correct mouse annotations from P2GO and move them into Noctua. Thanks, Li
