### ISSUE TITLE
Project review (last activity)

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#368]
As a last action before closing this project, I would like to collect thoughts on what worked and what didn't work (mainly technical, although anything is appreciated) for this project.

For example, chatting with @sierra-moxon, given everything that happened as part of the "MGI remainders" project that was the project before this, it may have been technically beneficial to just dump everything into a database first (including the expense of building that model and infrastructure), rather than continuing with the file shuffling. Things like this.

**Comment by sierra-moxon** [comment]
@kltm - should this be a go technical meeting or is the documentation on the gopreprocess repo in need of additional work?

**Comment by kltm** [comment]
@sierra-moxon This is just to have one last touching of bases with @pgaudet (the PO here) to make sure everybody is on the same page about what has been done and see if there is anything else to be done.

**Comment by kltm** [comment]
As well, if there is any future technical work that we'd like as a result of this project, we want to have tickets/stub projects for them.

**Comment by pgaudet** [comment]
@kltm is OK closing this.
