### ISSUE TITLE
Add "gopreprocess" pipeline to main pipeline workflows by code review

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#370]
@sierra-moxon has produced a pipeline branch to take the files that MGI previously used as their upstreams to produce our own proximate version. As a way of

- cleaning and renaming this branch
- doing a code review (@dustine32 and @kltm )
- adjusting metadata

we'll port the pipeline code to a new branch "manually" and make adjustments.

**Comment by sierra-moxon** [comment]
I believe this is done - the pipeline is called: https://build.geneontology.org/job/geneontology/job/pipeline/job/p2go-homology-upstream-file-generator/ and runs weekly on Mondays.
