### ISSUE TITLE
Pipeline failure on being unable to find MGI upstream

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#372]
The main build is now failing with the error:
```
18:09:08   - Trying again
18:09:22  Downloading http://www.informatics.jax.org/downloads/reports/gene_association_nonoctua.mgi.gz
18:09:22  Download of http://www.informatics.jax.org/downloads/reports/gene_association_nonoctua.mgi.gz failed: http://www.informatics.jax.org/downloads/reports/gene_association_nonoctua.mgi.gz:
18:09:22  2024-04-08 18:09:22 ERROR 404: Not Found.
```

Looking at http://www.informatics.jax.org/downloads/reports/, it just seems to be removed.

I'm assuming this is a consequence of the ongoing MGI "remainders" project, but I'm not sure what this would be connected to. I would have assumed that `gene_association_nonoctua.mgi.gz` would be available until the final parts of the switchover have been completed?

Tagging @sierra-moxon @pgaudet @leemdi @LiNiMGI

**Comment by leemdi** [comment]
this report was removed as part of the MGI-GOC project.  Now, GOC is generating the mgi.gpad and mgi.gaf file.
And we are not generating gene_association_nonoctua.mgi.gz, anymore.
if this needs to be discussed further, let me know (that is, a Zoom call).

**Comment by kltm** [comment]
@leemdi Good to know. My understanding was that things were going to be static (as in not change) until we completed 

https://github.com/geneontology/pipeline/issues/369
https://github.com/geneontology/go-site/issues/2285

and reported back. No worries, we can proceed with wrapping those up first.

**Comment by leemdi** [comment]
The MGI-GO data is static.  But we removed the reports that we used to generate.  David said it was OK to remove those public reports.  Li agreed.  This was all passed MGI-GO as part of our testing.  The reports are part of our MGI/GO pipeline. so we removed them.  If you still have the old gene_association_nonoctua.mgi.gz, then just use that.  I cannot product that file anymore.

**Comment by kltm** [comment]
@leemdi Understood--not a problem :) We're going ahead with manually getting https://github.com/geneontology/pipeline/issues/369 out the door, so we'll have our own SoT while we finish the transition.

**Comment by kltm** [comment]
Closing in favor of https://github.com/geneontology/pipeline/issues/373
