### ISSUE TITLE
Roll back (and then forward) "problematic" upstream files from selected resources

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#373]
We have four files that we want to roll back to the last "good" source, as represented in the last release.

- [x] tair: many issues, should be fixed week of May 1st
- [ ] mgi (see https://github.com/geneontology/pipeline/issues/372#issuecomment-2045194118) 
- [x] dicty: bad dictybase-unirpt mapping
- [x] pombase: to check
- [x] wormbase [EDIT: added]

Fastest path to get out fix for https://github.com/geneontology/amigo/issues/716

Tagging @pgaudet @dustine32

**Comment by kltm** [comment]
Blocked by https://github.com/geneontology/pipeline/issues/374 for the moment.

**Comment by kltm** [comment]
`snapshot` started.

**Comment by kltm** [comment]
I have confirmed with @vanaukenk that the FTP (and downloads HTTP) are down for WB.

**Comment by kltm** [comment]
Talking to @pgaudet last week, we'll be holding like this while she researches the issues (delta WB).

**Comment by kltm** [comment]
Noting that WB FTP still seems to be out of action. @vanaukenk, could I ask you to update here if that status changes?

**Comment by kltm** [comment]
Note from @vanaukenk that WB has recovered.

**Comment by kltm** [comment]
https://github.com/geneontology/go-site/pull/2302

**Comment by kltm** [comment]
@vanaukenk WB failing again:
```
01:10:56  Download of ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/annotation/gene_association/c_elegans.PRJNA13758.current.gene_association.wb.gz failed:  - Trying again
```
Reverting to our "safe" version.

**Comment by kltm** [comment]
Ah, I missed that the GPI is grabbed later for (the now unavailable) WB GPI. Reverting that as well.

**Comment by vanaukenk** [comment]
@kltm - I just tried the WB ftp site again and can manually download all of our files in the wb.yaml, so I'm not sure what's going on and if this is an intermittent thing.

If you want to look at this together in case I'm missing something, let me know.

**Comment by kltm** [comment]
@vanaukenk I can confirm that it's still not working for me and the pipeline machine, but I cannot confirm if there are firewall rules at my end or your end (yet). I'm happy to explore this with you at some point; hopefully we can deal with it at our leisure as your release frequency is low?

**Comment by vanaukenk** [comment]
Okay, thanks @kltm and very sorry for the continued trouble with the WB files.

Let me know when you'd like to meet and I could try to wrangle one of the WB developers, too, as that might also be a help.

**Comment by kltm** [comment]
I think MGI is good because we are now testing with our "internal" "upstream" source.
