### ISSUE TITLE
Bugs in GPI 2.0 format

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/pipeline#380]
Looking at the new GPI 2.0, specifically sgd.gpi on skyhook:

- [ ] Headers are missing required field: date-generated
- [ ] Headers are missing required field: generated-by
- [ ] Taxon field not using required `NCBITaxon:` prefix
- [ ] Object types are text labels not ontology IDs

**Comment by suzialeksander** [comment]
Currently file looks like 

> !gpi-version: 2.0
SGD:S000006369	RHO1	GTP-binding protein of the rho subfamily of Ras-like small GTPases	YPR165W|Rho family GTPase RHO1	protein	taxon:559292					
SGD:S000003211	ANK1	Cytoplasmic ankyrin repeat-containing protein	YGL242C	protein	taxon:559292					
SGD:S000002348	RBS1	Protein involved in assembly of the RNA Pol III complex	YDL189W|[VTS1+]	protein	taxon:559292					
SGD:S000028526	MCO10	Subunit l of the mitochondrial F1F0 ATP synthase	YOR020W-A	protein	taxon:559292

**Comment by kltm** [comment]
@sierra-moxon From our conversation earlier, while I found the GO API ticket for taxon/NCBITaxon, I actually couldn't find an output one. Did I remember that wrong?

**Comment by sierra-moxon** [comment]
just part of the checklist above :) I can write a test and then check it off, instead?  But the underlying problem with that is likely the change we just committed to the go-site db-xrefs.yaml file (now percolating through linkml/prefixmaps and ontobio, etc.)

**Comment by kltm** [comment]
Cheers--I was probably comflating something with https://github.com/geneontology/go-fastapi/issues/95
