### ISSUE TITLE
GPAD header suddenly changed 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/pipeline#383]
Reported by @alexsign

The latest GPAD files have this header: 
> !gpad-version: 1.2
!generated-by: GO Central
!date-generated: 2024-07-15T22:53

However the [documentation](https://geneontology.org/docs/gene-product-association-data-gpad-format/) (and all previous versions) state that it should be 
> !gpa-version

("gpa", not "gpad"). @alexsign fixed this manually on his end but it seems weird in our archive that we would change file headers.

**Comment by balhoff** [comment]
We did change this for 2.0, and it is in the spec, but it is wrong for earlier versions.

**Comment by kltm** [comment]
Which file was this?

**Comment by kltm** [comment]
This may be something that's from the fixes in the new ontobio code. Tagging on @sierra-moxon

**Comment by pgaudet** [comment]
@kltm 
> Which file was this?

any files on snapshot/annotation - for example dictybase
http://snapshot.geneontology.org/annotations/dictybase.gpad.gz

<img width="266" alt="image" src="https://github.com/user-attachments/assets/e9675a2a-cfc0-4519-b4b1-d3fbb5495b0c">

**Comment by kltm** [comment]
This is probably a hiccup in the new ontobio; tagging on @sierra-moxon .

**Comment by sierra-moxon** [comment]
yes this is my change.  will fix.

**Comment by sierra-moxon** [comment]
@kltm @pgaudet - on snapshot, all output GPAD in annotations directory should now be GPAD 2.0 - right? 
(there is still an issue here, if we are outputting 1.2 with the `!gpad-version` syntax, but I think the fix here is to figure out why we are outputting gpad 1.2 instead of 2.0)

**Comment by kltm** [comment]
@sierra-moxon on skyhook, we now have:
```
!gpad-version: 2.0
!generated-by: GO Central
!date-generated: 2024-07-28T14:31
```
This should propagate out to snapshot by sometime in the morning.
