### ISSUE TITLE
Python count and metadata sanity no longer seem to work

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#39]
Although there was a major GAF line reduction, the sanity checks did not prevent continuation.
geneontology/go-annotation#1997

**Comment by kltm** [comment]
The changes have been pushed into the pipeline. That means we should see a fail tonight?

**Comment by cmungall** [comment]
fixed upstream so we should see a pass

**Comment by kltm** [comment]
Can confirm the checks are working again with a couple of new error scenarios :)
