### ISSUE TITLE
Track down (and fix?) recent slowdown in the pipeline

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#50]
Recently--maybe Eric can fill in some details here--an ontobio release seems to have caused a ~50% (5hr) slowdown in the main mega Makefile step of the pipeline--from about 9hrs to 14hr-ish? It seems like it may have been a small change in caching or reporting that has caused this.

It is worrying for two reasons:
1) we now no longer have the ability to re-run the pipeline if failed during the same day and
2) it seems like it does not linearly scale (when compared to master/experimental run), meaning that more data in the future could make this even worse

tagging @dougli1sqrd

**Comment by dougli1sqrd** [comment]
So I have a proposed source of _some_ slowdown. In gorule-0000029 we check IEAs annotations' date to see if they are more than a year old. In the older version we were use the standard (and slow) `datetime.strptime()` function to parse the date: https://github.com/biolink/ontobio/commit/f1ce2e1289dccea9b1a5bc9bf8e79a7e04077d39#diff-ea0ca0cbbac794d7b79d23e5a8c4d7b6R63.

We could parse the string just as a set of digits though like we do earlier on in date parsing, forgoing the standard datetime function. I think we could see a noticeable speedup once this gets released and updated in go-site.

**Comment by cmungall** [comment]
no need to even convert to digits, if direct string comparison is faster (and simpler).

Also recommend calculating the threshold date once GAF, then comparing each against this (i.e. no subtraction necessary).

**Comment by kltm** [comment]
As a summary of the behind-the-scenes work from @dougli1sqrd : 

After playing with data and software versions, it seems that the issues are not likely to come from data, but rather a change in the software around that time. However, moving the software back to that point, with current benchmarks, we have only accounted for possibly 18% of the 50% slowdown (so 32% unaccounted for). We currently believe that the remainder is still something in the software, but tracking it down may be more complicated. This may make a good hackathon topic for a subgroup--profiling and code history. In the interim, if we want to "quickly" claw back some time from the slowdown, pursuing #24 would likely be more economical for now.

**Comment by kltm** [comment]
After some playing, it was decided that there were more economical ways to work on speeding up the pipeline. This is being suspended indefinitely.
