### ISSUE TITLE
Create a webhook for release (and possibly for snapshots internally)

### ISSUE THREAD

**Issue by lpalbou** [geneontology/pipeline#53]
Generally web hooks are more used to monitor changes in code repo such as GitHub, to triggers a rebuild, for instance on Jenkins.

However, in terms of both internal and external users, I was wondering if we should not create a webhook at the end of the pipeline, to inform any subscriber whenever a new release is available (or snapshot for internal usages). It could be useful for further integration / automation

What's your opinions ?

**Comment by kltm** [comment]
Honestly, I think the use cases for this are fairly narrow, and will be less so once the pipeline stabilizes. As the publication steps will all be in lock-step on release, including versioning information, I think there is not too much public use. For snapshots, they are every 24hr, barring disaster.

**Comment by lpalbou** [comment]
As briefly discussed during this morning call, I still think it would be useful for many reasons & applications:

1) the release can be delayed for any number of reasons, and even a monthly release seems "vague" in the sense: should it be available on the 1st of each month ? at what time ? it's ok but not automated and problems do occur

2) it would help the pipeline to focus on the delivery of primary products (release files) and not attempt to do everything, like a monolith.. it will be harder to follow & maintain the pipeline and additional features (which are not primary products) could actually crash the pipeline even though they are not essentials

3) we could have many secondary products handled by independent apps triggered by this web hooks, such as calling the GitHub API to update the README in the go-annoucement, or sending newsfeed, or updating the site, or even for us to check that the release has indeed not broken something in our development. Also, we could perform analytics and store the results in external database for each release (e.g. we don't really have something to keep track of the number of go-terms, annotated go-terms, go-cams, etc)

**Comment by kltm** [comment]
Actually, I'd say that for 2 & 3, the monolith is a feature, not a bug. We're currently finishing our migration from a more asynchronous/trigger system (almost there) and we've had nothing but increased understandability, reproducibility, speed, and turnaround times on features.

For 1, I agree that we should look at announce mechanisms and try to figure out what is needed/would be useful to the greater community. Even though in many cases people will be accessing `current` or AmiGO, which will have the DOIs imprinted on them already as-is (the versioning is built into people not being particularly aware of it in the first place), there are many places (such as triggering remote package rebuilds, as you mentioned) that we'll probably want to dig into a bit more to see what the community needs/wants.

**Comment by lpalbou** [comment]
@ktlm your pipeline should never crash because of the delivery of secondary products such as sending tweets (https://github.com/geneontology/go-site/issues/771). This is an extreme example but it's nonetheless true.

I would far more prioritize web hooks that could notify any number of applications (including sending tweets if you really want) than creating a manual api call to send a tweet at each release... 

On a more personal note, I would never think of checking tweeter to see if my database is updated... But I would dramatically use such webhook for all the secondary applications I mentioned above, including why not (crazy idea) to update any code or API using and/or ingesting for instance older version of GO

**Comment by kltm** [comment]
@kltm

**Comment by lpalbou** [comment]
That's strange, in my message it was lowercase.. I had to remove the tag and put it back again for it to display in lowercase, sorry about that.
