### ISSUE TITLE
IBAs are entering the data stream from goa_uniprot_all

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#60]
We would like the pipeline data flow to have a single source of IBA annotations, with PAINT, meaning that all IBAs that are non-PAINT in origin should be scrubbed.
We currently do this with all GAF inputs, excepting goa_uniprot_all. We'll need to add something that drops the IBAs before becoming a final product.
Options are to piggy back it on whatever we have doing the IEA filtering or to just have an easy awk or grep step to take care of it. I think the latter is fine; I've timed it on the order of minutes, so unlikely to affect pipeline timings in any significant way.

**Comment by pgaudet** [comment]
Please notify me when it's done so I can do some QC before this is public. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Looking at AmiGO and QuickGO: human have about the same numbers on both sites; however C. elegans and Drosophila have about 25-50% less annotations in AmiGO.

**Comment by kltm** [comment]
This will just re removing the ~million IBAs from that one file.

**Comment by kltm** [comment]
@dougli1sqrd This is clearing now, right?

**Comment by dougli1sqrd** [comment]
Yes, that should be present now.

**Comment by kltm** [comment]
Or, hopefully, not.
