### ISSUE TITLE
Port build.berkeleybop.org export-lego-to-gpad-sparql to give new home to GO-CAM pick-ups

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#65]
Currently, the only remaining core data product that we need that is not produced in the new pipeline is the GAF/GPAD from @balhoff at https://build.berkeleybop.org/job/export-lego-to-legacy/lastSuccessfulBuild/artifact/legacy/

Closing this would be porting that run command into the new pipeline as a parallel product build. Going with the PAINT pattern (paint_\*), we'd initially home it at /products/annotation/noctua_\* .

Looking to @cmungall for comment.

**Comment by kltm** [comment]
This would be the first step towards streaming the noctua go-cam data into the "main" GAF/GPAD products, like paint.

**Comment by kltm** [comment]
@balhoff Just an idle question while I test some initial runs. Overall, this seems to run a little slower than I would expect. Watching the resource usage, minerva seems to be fairly ginger, using little threading and memory. Ideally, we'd like to saturate the resources as much as possible for the pipeline. Obviously, we could just cut the work into chunks and do it ourselves (as this particular task is embarrassingly, delta the overhead), but I was wondering if there was anything that you might have in mind to increase efficiency or overall throughput?

**Comment by balhoff** [comment]
@kltm the modern job is actually https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/

We never turned off the previous GPAD export though.

**Comment by balhoff** [comment]
They're currently converted one-by-one, but there is no reason it can't be done in parallel. I'm less comfortable doing that in Java than in Scala, but I can try to figure it out.

**Comment by kltm** [comment]
Noting to @vanaukenk and @ukemi that we now have the active URLs in the pipeline, a la:
`http://current.geneontology.org/products/annotations/noctua_<RESOURCE>.gpad.gz`
`http://snapshot.geneontology.org/products/annotations/noctua_<RESOURCE>.gpad.gz`
`http://release.geneontology.org/<RELEASE_DATE>/products/annotations/noctua_<RESOURCE>.gpad.gz`
