### ISSUE TITLE
Zenodo updating should also include publication date, not just version

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#72]
To date, we have kept a constant initial publication date, while just updating the version for the GO archive and reference uploads into Zenodo. This causes some user confusion.

To close this, unless there is some compelling reason not to, we would like to update both the version and publication date to the date of the pipeline release.

**Comment by kltm** [comment]
Mostly concerning:
https://github.com/geneontology/go-site/blob/master/scripts/zenodo-version-update.py
https://github.com/geneontology/go-site/blob/master/scripts/zenodo-ops.py

**Comment by suzialeksander** [comment]
Tangential to https://github.com/geneontology/go-site/issues/789

**Comment by kltm** [comment]
Tested. I think we're good here.

**Comment by kltm** [comment]
To confirm on release.

**Comment by kltm** [comment]
Proven.
