### ISSUE TITLE
Ensure new PRO IDs are available via automated pipeline

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/pipeline#73]
I had created 6 new PRO ids and they became available in our MGI GO EI on Friday. That means they are in the mgi.gpi, (I verified) which I expected would then make them available in Noctua today but they are not there.
PR:000050039
PR:000050038
PR:000050037
PR:000050036
PR:000050035
PR:000050034

**Comment by kltm** [comment]
@hdrabkin The NEO pipeline is currently running only as a manual operation due to issues we had recently (see https://github.com/geneontology/neo/issues/38#issuecomment-451241964 ). We are working towards getting this into our pipeline, let's duplicate this onto #35

**Comment by hdrabkin** [comment]
Hi Seth
We have another new ID in our GPI that needs to get into Noctua
PR:A0A1W6AWH1

**Comment by kltm** [comment]
@hdrabkin I believe that this should be cleared on the completion of https://github.com/geneontology/neo/issues/38

**Comment by hdrabkin** [comment]
Hi Seth
Can we re-run to get in our most recent ids for Noctua use.
PR:000050193 and PR:000050194?
they are in our GPI

**Comment by kltm** [comment]
https://build.geneontology.org/job/geneontology/job/pipeline/job/issue-35-neo-test/18/

**Comment by kltm** [comment]
@hdrabkin This should be done.

**Comment by kltm** [comment]
@hdrabkin How recent is that? I put out a release on the 20th.

**Comment by hdrabkin** [comment]
It's very old now. This is the one I had mentioned before. The term was created 6/14/2019; it is not new. I  was just getting around to trying to curate it in Noctua now. I assumed the 7/25 fix would have fixed the issue.

**Comment by cmungall** [comment]
neo jobs failing on memory error
https://build.berkeleybop.org/job/build-noctua-entity-ontology/

**Comment by kltm** [comment]
Good catch, I forgot that we are not completing the circle with NEO yet. Perhaps we should just go ahead and put the old job to bed, we have a stub already for the S3 push: https://github.com/geneontology/pipeline/blob/issue-35-neo-test/Jenkinsfile#L213

There might still be timing issues with S3 updating, etc., but I can think of no real reason to keep the old job around. I'd propose that NEO is just another pipeline at the top level, functionally the same as https://github.com/geneontology/pipeline/blob/issue-35-neo-test/Jenkinsfile , or that we fold it into the main GO pipeline (which we tried a while back but got a little complicated).

**Comment by kltm** [comment]
@cmungall That said, any thoughts as to changes that would push it over the edge as far as memory goes over the last month?

**Comment by kltm** [comment]
@balhoff Unfortunately, @cmungall may not be available for a little bit. Would you happen to have any idea for the memory increase? If not, I'll probably move forward with getting the first idea above implemented.

**Comment by balhoff** [comment]
@kltm I updated the owltools memory allowance in the Jenkins job (`export OWLTOOLS_MEMORY=32G`) and started a run. We may want to move this into the NEO makefile itself. I'll see if the job is successful.

**Comment by balhoff** [comment]
Looks like we had a success.

**Comment by kltm** [comment]
@balhoff Awesome--I didn't know you had access. I'll rerun the side job and we can talk about getting rid of the legacy job when @cmungall is available.

**Comment by kltm** [comment]
Hrm.
@balhoff I just did a rollout and http://noctua-amigo.berkeleybop.org/amigo/term/PR:000050190 does not appear to be there. I'll try again tomorrow; if I fail, maybe we can make a little time to dig in to why that's not getting out?

**Comment by hdrabkin** [comment]
Have reverified that it IS in current GPI
grep of gpi
PR	000050190	mBMP2/iso:m2	bone morphogenetic protein 2 isoform m2 (mouse)		protein	taxon:10090	MGI:MGI:88177

**Comment by balhoff** [comment]
I'm guessing you get NEO via its inclusion within go-lego. I see this ID in NEO now, but it isn't yet in go-lego. We need a snapshot success for that.
