### ISSUE TITLE
Pipeline should use ODK for ontology builds instead of internally compiled software

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#76]
Possibly due to a change in a TSV, the go-ontology/src/ontology Makefile targets now often fail due to a requirement to run dosdp-tools, which are not compiled into our environment.

Talking with @cmungall and @dougli1sqrd , the desired solution is to rely on the ODK docker image as much as possible for the ontology build environment.

Related to #12, likely supersedes it.

**Comment by kltm** [comment]
@dougli1sqrd To complete this in the cleanest way possible (from a Jenkins pipeline perspective), we'd like ODK to supply the "rsync" command in the docker image. I've checked, and while it's not there, "scp" is available and may be usable in a pinch.

**Comment by kltm** [comment]
The docker image seems to supply the correct environment, commands would be something like:
```
cd /tmp
git clone https://github.com/geneontology/go-ontology.git
rsync /tmp/go-ontology/src/ontology/ ...
```

**Comment by dougli1sqrd** [comment]
https://github.com/INCATools/ontology-development-kit/pull/144
