### ISSUE TITLE
Test upcoming PANTHER 14.1 release

### ISSUE THREAD

**Issue by dustine32** [geneontology/pipeline#78]
Since we're releasing PANTHER14.1 sometime soon in Feb 2019, I'm pushing the updated tree files to our server for GO pipeline testing. This file is used in matching Panther families in amigo. The file will soon be available here:
http://data.pantherdb.org/PANTHER14.1/globals/tree_files.tar.gz

And I'll respond here once the file is in place.

On 14.1 launch day in Feb, we'll switch the `current` pointer to this new file, accessible here:
http://data.pantherdb.org/current/globals/tree_files.tar.gz

**Comment by kltm** [comment]
xref with https://github.com/pantherdb/Helpdesk/issues/3

**Comment by kltm** [comment]
@dustine32 Okay, if the run actually went how I think it went, it would mean that (holy cats!) the time-to-complete for the mega-Make went up about 3hrs, or nearly a 50% increase in run time for the longest running step...
@dougli1sqrd Would it be possible for you to take a look at the run and see if there is any way of discovering where the slowdown occurred? We can also run it again if it looks like something else might have happened.

**Comment by dougli1sqrd** [comment]
Ah yeah. Is this the whole resource set? I'll take a look.

**Comment by kltm** [comment]
After talking, will re-run to see if fluke.

**Comment by kltm** [comment]
@dougli1sqrd Nope, not a fluke, but a metadata whoops. The `make` command variable is actually different on the two runs--I initially branched off of master; the time difference is almost certainly due to not being able to run *quite* as parallel in the test (and again highlighting how awesome parallel make is for us).

@dustine32 If this, along with whatever the new GAFs will be, becomes the `current` release for you, it seems to cause only an extra hour (3h20m to 4h20m) of derivative production, mostly on the solr index, which seems to me to me in line with what we might expect for such a large expansion of your data. I know you've listed it elsewhere, but for posterity on this ticket could you give a very gross summary of the differences in the data?

**Comment by dustine32** [comment]
@kltm Basically, the difference is more genes. We added 20 more genomes, all plants, which typically have very large genomes. ~500,000 genes/IDs were added.

Also, if the pipeline parses each tree's hierarchy this might explain a lot of the increased processing time as some of the families increased in sequence count dramatically. Some examples:
* PTHR24015 grew from 2263 in 13.1 to 8402 in 14.1
* PTHR11926 grew from 2482 in 13.1 to 7016 in 14.1
* PTHR45613 grew from 1896 in 13.1 to 6976 in 14.1

**Comment by kltm** [comment]
Thanks--and with that let's close this out.

**Comment by kltm** [comment]
Noting your comment in https://github.com/geneontology/pipeline/issues/78#issuecomment-505207301 ,
unless the GAFs are significantly larger, there may not be a lot of change.

That said, if one were to test, one would change the metadata in https://github.com/geneontology/go-site/blob/master/metadata/datasets/paint.yaml and put it on an appropriate branch, where we would aim an experimental pipeline branch at it to pick up and test.

**Comment by dustine32** [comment]
@kltm Cool, thanks! I just created branch https://github.com/geneontology/go-site/tree/dustine32-issue-1127 with the updated URLs. Do I need to do anything in https://github.com/geneontology/pipeline to help trigger the test?

**Comment by kltm** [comment]
@dustine32 Okay, I've taken a look at the 14.1 runtimes in detail and I cannot see anything that raises a red flag. While the product creation increased by about half an hour, it seems to be with historical limits. As well, we did expect some increase and it wouldn't be a deal breaker.

**Comment by dustine32** [comment]
Noting here that today I switched the `current` symlink on our FTP server to point to Panther 14.1 data. This will change the set of tree files that the GO pipeline pulls. Now pointing to:
http://data.pantherdb.org/PANTHER14.1/globals/tree_files.tar.gz

Additionally, I uploaded a IBA GAF set to our normal drop-off location:
ftp://ftp.pantherdb.org/downloads/paint/presubmission/

This set of IBAs uses identifiers corresponding to the 14.1 tree files.

I'm intending on this running through `snapshot` for a couple weeks for testing before getting into `release`.

**Comment by dustine32** [comment]
@kltm Yep, there's quite a jump in IBA line count:
13.1 IBAs: 2468994
14.1 IBAs: 3360166

Though the 14.1 # is what was tested with [dustine32-issue-1127](https://github.com/geneontology/go-site/tree/dustine32-issue-1127) by pulling from ftp://ftp.pantherdb.org/downloads/paint/PANTHER14.1/presubmission/

I can try rerunning this branch.

**Comment by kltm** [comment]
@dustine32 Hey, neat find! I'll go ahead and start a trial, however maybe not right away as we are running a `master` test for the moment and we want to get a `snapshot` running tonight and we don't want to compete for resources at the moment.
