### ISSUE TITLE
Noctua gpad output has made a breaking change

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/pipeline#79]
I just noticed that the column 10 value in the gpad is now a URL instead of a user acronym
example
instead of MGI, is http:/www.informatics.jax.org
instead of SynGO, is https://syngo.vu.nl
This breaks our load.

Was this intended as the NEW format or is this unintended?

**Comment by kltm** [comment]
@balhoff Have there been any changes recently.
Also, @ukemi mentioned this.

**Comment by balhoff** [comment]
@hdrabkin where is the bad GPAD?

**Comment by hdrabkin** [comment]
http://snapshot.geneontology.org/products/annotations/noctua_mgi.gpad.gz

This one also has URLs instead of "MGI" in column 10

http://snapshot.geneontology.org/products/annotations/noctua_pr.gpad.gz

**Comment by balhoff** [comment]
I see, thanks!

**Comment by ukemi** [comment]
In comparison to the ones we are getting from the Jenkins build.

**Comment by ukemi** [comment]
Is there a pURL for the snapshot files?

**Comment by hdrabkin** [comment]
We are using this currently
 
build.berkeleyubop.org/job/export-lego-to-gpad-sparql/lastSuccessfuleBuild/artifact/legacy/mgi.gpad
build.berkeleyubop.org/job/export-lego-to-gpad-sparql/lastSuccessfuleBuild/artifact/legacy/pr.gpad

**Comment by balhoff** [comment]
This is an issue which I think resulted from porting the GPAD export job over from the old Jenkins to the new pipeline. The Minerva tool is being provided with go-gaf.owl, but it requires go-lego.owl:

https://github.com/geneontology/pipeline/blob/d290727ad96c1042f71ce614766608fc69408b41/Jenkinsfile#L51-L53

**Comment by kltm** [comment]
Checked with @dougli1sqrd , it looks like his checks indicate a fix on `minerva-go-lego`; will roll out to snapshot, etc. for tonight.

**Comment by hdrabkin** [comment]
Great; I'll look at the file tomorrow (we WERE attempting to be good and fetch the right file but ran into these issues)

**Comment by kltm** [comment]
@hdrabkin We had an unrelated pipeline failure and the new files are not up yet.

**Comment by dougli1sqrd** [comment]
@kltm here, I'm assuming this has gone through as no more activity.
