### ISSUE TITLE
Ensure that S3 headers match content

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#8]
Currently, the s3cmd auto-match seems to be failing in at least some cases. For example, YAML content header claims:
```http
'Content-Type': 'application/rdf+xml'
```

**Comment by cmungall** [comment]
ok, this should be a quick fix, @dougli1sqrd are you already on your travels, this is a high priority for the .obo files as it's confusing a lot of people

**Comment by kltm** [comment]
- [ ] csv - text/csv
- [ ] gaf - ???
- [ ] gz - application/gzip
- [ ] json - application/json
- [ ] md - text/markdown
- [ ] obo - ???
- [ ] owl - ???
- [ ] report - ???
- [ ] tsv - text/tab-separated-values
- [ ] txt - text/plain
- [ ] yaml - application/yaml
- [ ] yml - application/yaml

**Comment by kltm** [comment]
@dougli1sqrd @cmungall We need to get the above table filled out to proceed. Also, for the `.report` extension, that should actually have a `.txt` or `.md` extension, not `.report`.

**Comment by cmungall** [comment]
We always serve RDF/XML for OWL (we use other formats for source, but we always publish RDF/XML for consumers, as proposed https://github.com/OBOFoundry/OBOFoundry.github.io/issues/360)

so `application/rdf+xml` as mandated here:
https://www.w3.org/TR/REC-rdf-syntax/#section-MIME-Type

**Comment by kltm** [comment]
Talked to @cmungall , everything remaining will be `text/plain`, except for owl.
Now we just need to implement it and change `.report` to whatever it is.

**Comment by cmungall** [comment]
If `.report' is coming from ontobio GAF processing then we should rename this to be `.md`

**Comment by kltm** [comment]
Looking at how this is currently done in the pipeline, we'll probably want to write our own script to do this--walk the file tree from a point and push to AWS using the defined map above.

**Comment by kltm** [comment]
`!` changed to `NOT` in upstream.

**Comment by kltm** [comment]
boto working in some contexts, but not others.
```
      AttributeError: 'AWSHTTPSConnection' object has no attribute 'ssl_context'
```
Likely due to some versioning problems with the library (e.g. https://github.com/boto/botocore/issues/1258). Trying to figure out why this works on my local machine, but not wok.

**Comment by kltm** [comment]
This might be it: the use of certbot on wok upgrades some packages to the point of not working for this:
      remote:
      python3-urllib3 is already the newest version (1.21.1-1+ubuntu16.04.1+certbot+1).
      local:
      python3-urllib3 is already the newest version (1.13.1-2ubuntu0.16.04.1).

**Comment by cmungall** [comment]
```
$ wget http://purl.obolibrary.org/obo/go/go-basic.obo -O /dev/null
--2018-02-02 12:30:53--  http://purl.obolibrary.org/obo/go/go-basic.obo
Resolving purl.obolibrary.org (purl.obolibrary.org)... 52.3.123.63
Connecting to purl.obolibrary.org (purl.obolibrary.org)|52.3.123.63|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://snapshot.geneontology.org/ontology/go-basic.obo [following]
--2018-02-02 12:30:53--  http://snapshot.geneontology.org/ontology/go-basic.obo
Resolving snapshot.geneontology.org (snapshot.geneontology.org)... 52.84.245.169, 52.84.245.4, 52.84.245.217, ...
Connecting to snapshot.geneontology.org (snapshot.geneontology.org)|52.84.245.169|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 33792340 (32M) [application/rdf+xml]
Saving to: ‘/dev/null’
```

**Comment by kltm** [comment]
Corrected in master, waiting on release/snapshot merge.

**Comment by kltm** [comment]
Okay, I'm pretty sure the response will be that it is still affecting users, so not done. OTOH, users are generally not in this repo and the tracker still needs to be useful for managing work otherwise. Since having shadow tickets is really annoying, how about a new project category that's "pending" or the like, allowing closure, but not entry into the done category--this allows us to continue using the tracker as an actually tracker and not zendesk, but still give useful reports and overviews.
