### ISSUE TITLE
Pipeline fails on ontobio errors

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#81]
In some cases, ontobio fails downloads with unexpected headers.

**Comment by kltm** [comment]
See https://github.com/biolink/ontobio/pull/293

**Comment by dougli1sqrd** [comment]
From earlier (that the above PR fixes):
Looks like something is wrong with pseudocap. Part of the error though is has to do with a bug in the python - exposed by a bad response from a web request.
So for some reason when downloading pseudocap the Content-Length header isn't set in the response? Ultimately this is a None bug, and is crashing on a None value. So the Content-Lenght is weird, but it shouldn't be crashing ontobio.

**Comment by kltm** [comment]
Looks like we have cleared the problems!
