### ISSUE TITLE
Push GAF files into Alliance submission system

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#83]
Currently, there is a manual step within the AGR pipeline to draw in GAFs needed for gene description. To make sure things stay more in sync, the proposal is to have the `release` deployment stage of the pipeline push into the AGR submission system.

@sierra-moxon to dig more into this, from the files listed here (http://current.geneontology.org/annotations/), which ones would be the ones of interest? As well, is there some current submission API documentation to look at?

**Comment by sierra-moxon** [comment]
mgi.gaf.gz
rgd.gaf.gz
zfin.gaf.gz
wb.gaf.gz
fb.gaf.gz
sgd.gaf.gz

plus a human gaf with HGNC ids.

**Comment by kltm** [comment]
@sierra-moxon We currently don't have any GAFs with HGNC IDs that I know of, although that is under discussion (https://github.com/geneontology/go-site/issues/756). The others should be easy enough.

For the API, I haven't been able to track anything down on the site.

**Comment by sierra-moxon** [comment]
https://github.com/alliance-genome/agr_java_software/blob/develop/agr_api/Submission_README.md

I can give you the key offline :).  Unzipped versions for the submission are required at the moment.

**Comment by kltm** [comment]
@sierra-moxon So, something then like:
```
curl \
	-H "api_access_token: FOOBARBIBBLE" \
	-X POST "https://www.alliancegenome.org/api/data/submit" \
	-F "1.0.0.8_GAF_7227=@/foo/bar/fb.gaf" \
	-F "1.0.0.8_GAF_10090=@/foo/bar/mgi.gaf" \
	-F "1.0.0.8_GAF_10116=@/foo/bar/rgd.gaf" \
	-F "1.0.0.8_GAF_4932=@/foo/bar/sgd.gaf" \
	-F "1.0.0.8_GAF_6239=@/foo/bar/wb.gaf" \
	-F "1.0.0.8_GAF_7955=@/foo/bar/zfin.gaf"
```

Notes to self: grab from skyhook, zip, hard-coded POST.

**Comment by sierra-moxon** [comment]
Yep, that looks right.  I have had some timeout issues doing all files at once, but I'm sure that will improve in coming releases (and you might be able to get all the GAFs in one call, depending on size)

**Comment by kltm** [comment]
@sierra-moxon Okay, so code that may work is in place, but I'll want to test it before adding it to the release code. How often are you wanting these files? I figure you'd want the monthly releases, but the daily ones are available as well.
After our next release (today or tomorrow), we'll have until the end of the month to figure out how to test. Is there perhaps a dummy submission service that could be tested against?

**Comment by sierra-moxon** [comment]
Dummy system is definitely a need: we don't have one in place for 2.1 release, but will for 2.2.   To be clear, single file submission works well at the moment, but depending on the size of the files in a multi-file 'push', I have had some time outs.  Doing 6 individual 'pushes' of GAF files worked well for me.  Good question w/re to daily or monthly - right now Alliance is on a quarterly data release but that will probably change soon.  I'll try to keep tabs on the latest w/re to data releases and let you know.

**Comment by kltm** [comment]
I'm not so worried about timeouts so much as debugging the code that sits at the end of a very long pipeline.
Ideally, for the rest of the month, or just for next week, we could push `snaphot` into your system for testing, then once debugged, switch over to `release` only. Snapshots are identical to releases, except that they are not archived and have no related DOI; I suspect they are no worse than the files you have now. If that works, I'll go ahead with testing.

**Comment by sierra-moxon** [comment]
I'm not sure I completely understand the difference - mostly because Alliance code is just consuming files from the S3 Alliance bucket at this point.  The current system just takes the most recent when its told to.  So, whichever files you find most appropriate, you can just push them up and we'll use them.  If we swap over to a pull system (my preference), we could figure out which is best using your guidance.

**Comment by kltm** [comment]
@sierra-moxon The question is about version synchronization and how things can be reproduced. It sounds like it is probably a grab bag at this point, so I'll go ahead and use snapshot as a test bed.

**Comment by kltm** [comment]
New pattern for upload supplied by @sierra-moxon : 

f you want to automate GAF update pushes to alliance - use this method:
```
curl -H "Authorization: Bearer 
+ authentication token +
-X POST "https://fms.alliancegenome.org/api/data/submit" -F "1.0.0.8_GAF_" 
+ MOD-abbreviation +
 "=@" + localFilename 
```
For testing, information supplied by @sierra-moxon :

instead of *fms.alliancegenome.org*, you can use the same doc with *fmsdev.alliancegenome.org* that will be overwritten completely once a week with prod data. Viewing results can be done via swagger endpoints, or by looking at the S3 bucket directly (*downloaddev.alliancegenome.org* <-- dev or *download.alliancegenome.org* <-- prod). Swagger endpoints are: fmsdev.alliancegenome.org/swagger-ui/index.html (and fms.alliance.... <-- prod).

**Comment by kltm** [comment]
In conversation with @sierra-moxon , I believe that they will be going to a pull system, so this is no longer needed.
