### ISSUE TITLE
GeneDB, JCVI and other sources seem to be loaded twice

### ISSUE THREAD

**Issue by pgaudet** [geneontology/pipeline#85]
hello, 

We seem to have the duplicate entry problem sneaking in again: For example: GeneDB:PF3D7_1105600 and UniProtKB:Q8IIU7

Also: JCVI_CMR:PFL_1630 -> the link to JCVI is dead, and AFAIK we cannot edit the records that have not been loaded via GOA. 

I suspect that we are loading the old files directly AS WELL AS from GOA; can we ONLY load the GOA ? 

Thanks, Pascale

**Comment by kltm** [comment]
Is this a request to remove metadata/datasets/jcvi.yaml?

**Comment by cmungall** [comment]
@alexsign can you confirm that both the GeneDB and JCVI annotation files are all loaded into UniProt-GOA, and that there would be no information loss if these GAFs were to be dropped?

**Comment by pgaudet** [comment]
> Is this a request to remove metadata/datasets/jcvi.yaml?
I think so, but given that I don't quite know where the data is coming from I would like you to confirm that this is what is causing the duplicated data.

**Comment by alexsign** [comment]
@cmungall yes, both are loaded into UniProt-GOA

**Comment by alexsign** [comment]
Here is the full list of GOA sources:
[GOA_sources.xlsx](https://github.com/geneontology/pipeline/files/2966455/GOA_sources.xlsx)

**Comment by pgaudet** [comment]
> If the source type indicates "internal" it is updated though Protein2GO, others loaded periodically. Please let me know if you have any questions.

**Comment by pgaudet** [comment]
@alexsign 
Is all this data (internal, external and automatic) in the files you export ?

**Comment by alexsign** [comment]
@pgaudet yes, but the one that passed all sanity checks

**Comment by pgaudet** [comment]
>  only the one that passed all sanity checks

The annotations ? or do you apply the same to all annotations from a given source ?

**Comment by pgaudet** [comment]
The JCVI data is now fully loaded from GOA. The JCVI files have been removed from the datasets.yaml
