### ISSUE TITLE
Shift from current to released versioned of PANTHER

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#86]
To help make the lives of @dustine32 easier when making releases, we'd like to shift from always using the current PANTHER release (and begging to not release at certain times) to a versioned release where we are the masters of our own destinies.

@dustine32 will provide URLs for the current and next releases so that we can test them. We should move to the current current immediately, and the future current after the EOTM release.

**Comment by dustine32** [comment]
Thanks @kltm ! Right now, you can point to:
http://data.pantherdb.org/PANTHER13.1/globals/tree_files.tar.gz

Once we update the PAINT GAFs to reflect the new version of Panther, the tree files can start being pulled from:
http://data.pantherdb.org/PANTHER14.1/globals/tree_files.tar.gz

**Comment by kltm** [comment]
@dustine32 And what about the GAFs that we'll need aligned with that release?

**Comment by dustine32** [comment]
@kltm I don't think anything extra will need to be done with the GAFs on your end. It's just that, through the tree files, the identifiers in the PAINT GAFs will start pointing to the PANTHER families they're associated with in 14.1 vs 13.1.

**Comment by kltm** [comment]
Right, so we would be loading a "14.1" GAF, with fields that contain things like `PANTHER:PTN001806046`, which would be referencing a node in what version of PANTHER? My understanding is that these are not persistent across releases. If the trees do not line up with the given annotation information there could be some weirdness.

**Comment by dustine32** [comment]
Correct, the node `PTN#`'s can move to different families/trees across release. For the 14.1 GAF, the data contained should be referencing Panther 14.1 families/trees.

**Comment by kltm** [comment]
@dustine32 So we'd need both a 13.1 version of the trees and GAFs, implying that both would be versioned for us, right?

**Comment by dustine32** [comment]
I guess I didn't intend on concurrently having two versions of GAFs that vary by the Panther version they're based on. We currently don't version where we submit the PAINT GAFs for the GO pipeline (e.g. ftp://ftp.pantherdb.org/downloads/paint/13.1/presubmission/ doesn't exist). So I just assumed that the data in the PAINT GAFs would change when we generate them off of the converted, 14.1-based PAINT annotations, and then amigo would start using the 14.1 trees.

The part I'm missing from my assumption is how (the trigger) amigo would know to start pulling from 14.1 vs 13.1 tree files. There may be a Panther version # in the IBA GAFs. I'll check right now.

**Comment by dustine32** [comment]
@kltm Yup, it's in our IBA GAF header:
```
!PANTHER version: v.13.1.
```

**Comment by kltm** [comment]
Talked to @dustine32 a little bit about this.

* We are unlikely to move on any major changes to how we do things for the moment
* We agree that a more "version aware" way of doing things would be useful, but it may require some work within the PANTHER pipeline first
  * Until then, we'll just work out how to coordinate releases the "old fashioned" way ("Hey, you...")
* If we want to moved away from the current single drop point system we have now we would need/want to do *one* of the following two things:
  * have both versioned URLs for the IBA GAFs as well as the tree files
  * use universally resolvable identifiers (PTNs) that are not reused across versions--this would allow the trees and GAFs to change independently

**Comment by dustine32** [comment]
@kltm We have a "test" set (it's pretty much our real dataset) of PAINT IBA GAFs for Panther 14.1 ready to go. It's sitting here:

ftp://ftp.pantherdb.org/downloads/paint/PANTHER14.1/presubmission/

Would I need to hook this into a metadata file in go-site somewhere?

**Comment by kltm** [comment]
I think this may be more about https://github.com/geneontology/pipeline/issues/78

That said, once finalized, if this was given it's own perma-URLs, this would fit the "requirements" for this ticket.

**Comment by kltm** [comment]
TODO: Add PANTHER_VERSION AA.B and PAINT_RELEASE XXXX-YY-ZZ variables:
https://github.com/pantherdb/fullgo_paint_update/issues/34#issuecomment-529229852
Tagging @dustine32

**Comment by kltm** [comment]
Noting that moving forward on this is essentially a requirement as PANTHER is staggering out the release and we need to sit on 14.1.

**Comment by kltm** [comment]
@dustine32 How do you feel about this ticket here. Is this something that we're likely to pursue, or is this a bit of a dead end now?

**Comment by dustine32** [comment]
@kltm If I understand this correctly, we are now doing this anyway. All PAINT IBA GAF releases are now accessible via paths based on their PANTHER version and release date, e.g., [17.0/2022-11-04](http://data.pantherdb.org/ftp/downloads/paint/17.0/2022-11-04/), [15.0/2022-09-26](http://data.pantherdb.org/ftp/downloads/paint/15.0/2022-09-26/). If we want to test a future release before it's "released" (using the `current` and `presubmission` symlinks on the PAINT FTP server), I can put the files in place and we can target the specific release path, like what we're doing with `17.0/2022-11-04` in https://github.com/geneontology/go-site/issues/1926.

Short answer: I think this can be closed.

**Comment by kltm** [comment]
@dustine32 I guess the question for me boils down to 
https://github.com/geneontology/pipeline/blob/92ee61190cffcd14f30a8d38f807bd4b7083abab/Jenkinsfile#L75-L78
and
https://github.com/geneontology/pipeline/blob/92ee61190cffcd14f30a8d38f807bd4b7083abab/Jenkinsfile#L762-L763
To clarify what you're saying from my POV: we'll do direct dating in the metadata, but drop the idea of VERSION and RELEASE being separable identifiers? So I can eliminate the currently unused `PAINT_RELEASE`.

**Comment by dustine32** [comment]
@kltm Oh yes, correct. You can get rid of `PAINT_RELEASE`. VERSION and RELEASE are pretty much inseparable.
