### ISSUE TITLE
Dates in ontology header must accurately reflect the creation date

### ISSUE THREAD

**Issue by ukemi** [geneontology/pipeline#90]
On 2019-04-24 I downloaded the go.obo file. Although the snapshot summary shows Tue Apr 23 00:01:31 PDT 2019 as the production date, the go.obo file has this in the header:
data-version: releases/2019-04-18

If the snapshot build is successful, shouldn't the file headers be consistent with the build date.

**Comment by kltm** [comment]
Notes: on 2019-04-23, the go.obo header field read:
`data-version: releases/2019-04-18`
Same for: https://s3.amazonaws.com/go-data-product-snapshot/ontology/go.obo , last updated on April 23rd.

Going back through the snapshot dailys:

* 12th is 11 
* 17th is 17
* 18th is 18
* 20th is 18
* 21st is 18
* 22nd is 18
* 23rd is 18

Today's (incomplete/failed) snapshot is `releases/2019-04-24` (24). So the problem may have "corrected" itself. 

I believe that something make have gotten somehow stuck or cached in the ontology build part, but is generally okay. As it has already "corrected", we cannot identify where it is coming from now. I believe the appropriate response is to add a bit to the pipeline ontology build step that pulls the date and matches against the current run date, emailing if there is an anomaly. Also, somebody should eyeball that code real fast to make sure it's pulling/creating the date properly.

**Comment by balhoff** [comment]
> Also, somebody should eyeball that code real fast to make sure it's pulling/creating the date properly.

https://github.com/geneontology/go-ontology/blob/b6b48516989222bf24706de65086490007ec4b00/src/ontology/Makefile#L61

**Comment by cmungall** [comment]
Looks correct

**Comment by balhoff** [comment]
@kltm just an observation that the current ontology release, `http://purl.obolibrary.org/obo/go/releases/2019-06-10/go.owl`, is not available from its version IRI. The release was dated the day before: http://release.geneontology.org/2019-06-09/ontology/index.html

**Comment by kltm** [comment]
@balhoff My theory for the moment is that the ODK may be somehow locked into a different timezone. I think an easy workaround would be that the ontology build takes an explicit argument from its environment.

**Comment by kltm** [comment]
@balhoff Should there be another ticket for the the ODK in ontodev or go-ontology, a la https://github.com/geneontology/pipeline/blob/master/Jenkinsfile#L332 , to take the "correct" date to use for th build?

**Comment by kltm** [comment]
Noting notice on upstream issue: https://github.com/INCATools/ontology-development-kit/issues/232

**Comment by kltm** [comment]
@dougli1sqrd It looks like the fixes have been merged. Would you know if there is a new ODK image that we can use?

**Comment by dougli1sqrd** [comment]
https://github.com/INCATools/ontology-development-kit/pull/233 is still open currently, but can probably be merged shortly. Then we'll have to make a new ODK image I guess.

**Comment by kltm** [comment]
I've restarted `release` again. Worst case is that @balhoff will have to add another redirect.
We should have this all squared away before next release however.

**Comment by kltm** [comment]
@balhoff Assuming we use the current release, it looks like it got the right date this time.

**Comment by kltm** [comment]
Duped onto #123
