### ISSUE TITLE
Tomato annotations missing from goa_uniprot_all.gaf

### ISSUE THREAD

**Issue by dustine32** [geneontology/pipeline#92]
All taxon:4081 (tomato) annotations (around 141805 total) appear to have gone missing from the huge goa_uniprot_all.gaf in every GO release starting with the 2019-02-01 GO release GAFs. This pretty much wiped out all of our tomato annotations in Panther.

Just now checking the goa_uniprot_all.gaf that I downloaded from the GOA [upstream URL](ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gaf.gz) I do find 35961 taxon:4081 lines. Though it's a 75% reduction from the count in the 2019-01-01 GO release so maybe something was going on at EBI upstream?

But actually, comparing the headers of the file I downloaded from EBI with the goa_uniprot_all.gaf in the 2019-04-17 GO release, the timestamp is the same: "2019-04-08 11:50", but the EBI version has the tomato lines whereas the GO version doesn't. There's also about 1 GB diff in file size. Shouldn't these files be identical or is there some processing on it in the GO pipeline?

Tagging @kltm .

**Comment by kltm** [comment]
This, at least recently, does not appear to be in the data at all in our produced data:
```
grep 'taxon:4081' goa_uniprot_all_noiea.gaf  | wc
      0       0       0
grep [[:space:]]taxon:4081[[:space:]] goa_uniprot_all.gaf  | wc
      0       0       0
```
@dougli1sqrd for `goa_uniprot_all.gaf`, what, if anything, do we change versus the upstream?

**Comment by kltm** [comment]
Okay, it looks like us:
```
grep [[:space:]]taxon:4081[[:space:]] goa_uniprot_all-src.gaf | wc
  35961  568627 6139907
grep [[:space:]]taxon:4081[[:space:]] goa_uniprot_all-src.gaf | grep [[:space:]]IEA[[:space:]] | wc
  31402  497782 5000096
```
Let's talk after the meeting, @dougli1sqrd

**Comment by kltm** [comment]
Talking to @dougli1sqrd , we want to make sure we have enough information to potentially stop the pipeline ahead of time in these cases, see: #93 

We currently believe that this is either due to a change in the columns of the the taxon:4801 annotations (and may not be limited to them) or something wonky in the taxon filtering.

**Comment by kltm** [comment]
Refenencing the check at https://github.com/geneontology/go-site/blob/master/pipeline/util/goa_filter#L23
```
grep [[:space:]]taxon:4081[[:space:]] goa_uniprot_all-src.gaf > tomato.gaf
head -1 tomato.gaf | awk -F'\t' '{print NF; exit}'
17
```
@dougli1sqrd It would seem to be passing that test, which would mean the issue is in the taxon handling. Shall we touch bases again?

**Comment by kltm** [comment]
@dustine32 The way things get filtered, it seems that we are "correct", at least as far as our metadata goes. According to our metadata, sgn (sgn.yaml) handles taxon:4081, so we filter them from goa\_uniprot\_all as that are "in charge" of tomatoes. (@cmungall put this in place initially, so I assume that this is correct.)

Are you sure you're sure that these changes have taken place and it's not at your end? I can't seem to find any *current* problem in our system with my current understanding of what's going on.

**Comment by dustine32** [comment]
Perhaps @cmungall 's changes happened between the 2019-01-01 and 2019-02-01 GO releases since that's when I see taxon:4081 lines disappearing from the GO release goa_uniprot_all.gaf?

This method does seem to be the most correct if SGN is required to handle all tomato annotations, including IEAs. I'll talk with @huaiyumi about taking it up with SGN. Thanks!

**Comment by kltm** [comment]
I'm going to do some spot checking now for what we had in the past, but as it currently stands right now, we are correct according to our metadata. It *may* be that we erroneously included 4081 previously, but that seems to no longer be the case--things seem to be working as they should right now (at least on `snapshot`, I'm going to do a few more samples.

**Comment by kltm** [comment]
@dustine32 I've checked last year, January, and the last release--I don't think we've ever had these as product:
```
grep [[:space:]]taxon:4081[[:space:]] goa_uniprot_all.gaf_2018-05-20 | wc
      0       0       0
grep [[:space:]]taxon:4081[[:space:]] goa_uniprot_all.gaf_2019-01-01 | wc
      0       0       0
grep [[:space:]]taxon:4081[[:space:]] goa_uniprot_all.gaf_current  | wc
      0       0       0
```

I think there might be something else going on, but this is behaving as expected and has historically been done.

**Comment by cmungall** [comment]
I check the 2018-12-01 release, looked at the release product goa_uniprot_all.gaf.gz, no tomato

`gzip -dc ~/Downloads/goa_uniprot_all.gaf.gz | cut -f13 | egrep ^taxon:4081$`

Are you sure it used to be present @dustine32 ?

**Comment by dustine32** [comment]
@cmungall @kltm Hm, weird. I still get 141805 from whatever goa_uniprot_all.gaf file is sitting in our update folder that should contain the 2019-01-01 GO release GAFs. I'm actually doing a 2-part, dumb grep where I grep out any lines containing taxon:4081 (so it includes all the other "taxon:4081*" crud) into a file, then `sort | uniq -c` this file and I get `141805 taxon:4081` at the top. Don't know if that process falsely skews my results. But to make sure, I'm redownloading the 2019-01-01 GO release file and rechecking.

However, I agree if there's a dataset yaml (sgn.yaml) saying they're in charge of tomato annotations, they should have all of them in their file. They may actually be in there but just use a different non-UniProtKB identifier that we can't currently map to Panther genes. Gonna bring this up with Huaiyu in our group meeting tomorrow. Thanks!
