### ISSUE TITLE
Ontology release and snaphot seems to be out of phase with current state of ontology

### ISSUE THREAD

**Issue by krchristie** [geneontology/pipeline#95]
Hi,

I am trying to add annotations to a new GO term that I committed two weeks ago (stanza from go-edit.obo included below)

The term was added on 4/26/19, but when I try to use it, either in the existing model that already contains the other annotations from the paper, or in a new one, either using the form or the graph editor (either as an individual or as a process term), it is not available in the autocomplete.

How long should I expect to wait for a new term to be available? 

thanks,

-Karen

```
[Term]
id: GO:0120197
name: mucociliary clearance
namespace: biological_process
def: "The respiratory system process driven by motile cilia on epithelial cells of the respiratory tract by which mucus and associated inhaled particles a\
nd pathogens trapped within it are moved out of the airways." [GOC:krc, PMID:24119105, PMID:27864314]
synonym: "MCC" RELATED [PMID:24119105, PMID:27864314]
synonym: "MCT" RELATED [PMID:28289722]
synonym: "mucociliary transport" EXACT [PMID:28289722]
is_a: GO:0003016 ! respiratory system process
is_a: GO:0003351 ! epithelial cilium movement involved in extracellular fluid movement
created_by: kchris
creation_date: 2019-04-26T16:16:50Z
```

**Comment by kltm** [comment]
Noting that https://github.com/geneontology/pipeline/issues/95#issuecomment-498459607 would also be consistent with an env/owltools issue--I'll start pulling that apart next.

**Comment by cmungall** [comment]
Nothing to do with owltools, as we don't use owltools for the merge

I have tracked to an issue with robot: https://github.com/ontodev/robot/issues/493

**Comment by kltm** [comment]
@cmungall To clarify, the theory was *not* that it was owltools merge, but that the docker environment was not correctly picking up the external variable and using fallbacks, which would them point them to the last release...or something. The debugging that started was making the environment more verbose about what it actually contained. After *that* I would be back to owltools itself and water sprites if Jim had not found anything at his end. It sounds like it has worked out though :)
